In [1]:
%matplotlib inline

In [42]:
import os

models_path='sklearn-models'
model_name='LinearSVM'
output_path='output.csv'
dataset_path='/home/aboelhamd/Downloads/sklearn-svm/sklearn-nobad'
files = {}
# r=root, d=directories, f=files
for r, d, f in os.walk(dataset_path):
    for file in f:
        files[file]=os.path.join(r, file)

# os.mkdir('models')

In [3]:
### import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.externals import joblib
from sklearn.preprocessing import OrdinalEncoder


for file in files:
    # These are the classifiers that permit training data with sample weights!
#     names = ["NaiveBayes", "LinearSVM", "RBFSVM", "DecisionTree",
#          "RandomForest", "AdaBoost"]
    
    print("file name :", file)
    data = pd.read_csv(files[file], delimiter=r"\s+", header=None).dropna()
    
    # words (features) encoding
    # load the encoder
    enc = joblib.load(models_path+'/'+'encoder'+'-'+file[:-4])
    # remove records with unseen word, will return always 0 for that record
    # this will be solved later
    unseen = []
    for i in range(len(data.values)) :
        for j in range(len(data.values[i])) :
            if data.values[i][j] not in enc.categories_[j] :
                unseen.append(data.values[i])
    
    seen = [x for x in data.values if x not in unseen]

    samples = enc.transform(seen)
    
#     print("file name :", file)
#     print("Rules(classes) number :",target.nunique())
    print("Words(features) number :",samples.shape[1])
    print("Records number :",samples.shape[0], end = '')
#     display(data.iloc[:target.nunique(),:])
    
#     display(features, target, weights)
    
    # prediction by using svm
#     print("model :", name, ",", end = '')
    name = 'LinearSVM'
    modelname = models_path+'/'+name+'-'+file[:-4]+'.model'
    loaded_model = joblib.load(modelname)
    rules = loaded_model.predict(samples)
    # insert zero in unseen data
    for i in range(len(data.values)) :
        if data.value[i] in unseen :
            rules.insert(i,0)

    # write results in file
    output = open(output_path, 'w+')
    for rule in rules :
        output.write(rule+"\n")
    
    print("----------------------------------------------\n")

file name : 40+68_63+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 276

   rule  weight  word1 word2
0     0     0.5  haber   ser
1     1     0.5  haber   ser

model : NaiveBayes , score = 0.45654482962107334
model : LinearSVM , score = 0.4637975614023888
model : RBFSVM , score = 0.31829418475530613
model : DecisionTree , score = 0.3836062964213818
model : RandomForest , score = 0.38350158147992314
model : AdaBoost , score = 0.3617831020952113
----------------------------------------------

file name : 27+21_106_29+10_30_106_29+10_110_29_106_29+11_30_106_29+11_110_29_106_29+33_1_30_106_29+33_1_110_29_106_29+.csv
Rules(classes) number : 8
Words(features) number : 6
Records number : 120

   rule    weight word1       word2 word3  word4 word5     word6
0     0  0.137765   uno  aportación   muy  claro     y  positivo
1     1  0.128679   uno  aportación   muy  claro     y  positivo
2     2  0.119732   uno  aportación   muy  claro     y  positivo
3     3  0.119732   uno  aportación   muy  claro     y  positivo
4     4  0.127315   uno  aportación   muy  claro     y  positivo
5     5  0.127315   uno  aportación   muy  claro     y  positivo
6     6  0.119732   uno  aportación   muy  claro     y  positivo
7     7  0.119732   uno  aportación   muy  claro     y  positivo

model : NaiveBayes , score = 0.06703474247602752
model : LinearSVM , score = 0.10093532974509636
model : RBFSVM , score = 0.11605573183596676
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.033775670441412345
----------------------------------------------

file name : 13+37_12+37_113_1+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 117

   rule    weight  word1 word2 word3
0     0  0.352679  hacer    50   año
1     1  0.323660  hacer    50   año
2     2  0.323660  hacer    50   año

model : NaiveBayes , score = 0.2942577385293566
model : LinearSVM , score = 0.3158541827161679
model : RBFSVM , score = 0.3532454955917427
model : DecisionTree , score = 0.17141174651482455
model : RandomForest , score = 0.1712896936630942
model : AdaBoost , score = 0.1694033114534203
----------------------------------------------

file name : 76_64+76_91+76_108_68+75_67+75_63_64+75_63_91+75_63_108_68+100_40_64+100_40_91+100_40_108_68+100_37_67+100_37_63_64+100_37_63_91+100_37_63_108_68+.csv
Rules(classes) number : 14
Words(features) number : 5
Records number : 56

    rule    weight word1  word2   word3 word4    word5
0      0  0.073716    no  haber  hablar    de  emplear
1      1  0.071830    no  haber  hablar    de  emplear
2      2  0.070473    no  haber  hablar    de  emplear
3      3  0.070710    no  haber  hablar    de  emplear
4      4  0.070710    no  haber  hablar    de  emplear
5      5  0.069735    no  haber  hablar    de  emplear
6      6  0.070710    no  haber  hablar    de  emplear
7      7  0.072360    no  haber  hablar    de  emplear
8      8  0.071338    no  haber  hablar    de  emplear
9      9  0.070000    no  haber  hablar    de  emplear
10    10  0.072360    no  haber  hablar    de  emplear
11    11  0.072360    no  haber  hablar    de  emplear
12    12  0.071338    no  haber  hablar    de  emplear
13    13  0.072360    no  haber  hablar    de  emplear

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.07381804243862623
model : RBFSVM , score = 0.07381804243862623
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 67+63_64+63_91+63_108_68+.csv
Rules(classes) number : 4
Words(features) number : 3
Records number : 116

   rule    weight     word1 word2     word3
0     0  0.254216  encargar    de  elaborar
1     1  0.254216  encargar    de  elaborar
2     2  0.247765  encargar    de  elaborar
3     3  0.243803  encargar    de  elaborar

model : NaiveBayes , score = 0.13992349932223666
model : LinearSVM , score = 0.19246829395922085
model : RBFSVM , score = 0.237588422251646
model : DecisionTree , score = 0.07014294386464993
model : RandomForest , score = 0.051613671230843566
model : AdaBoost , score = 0.12037676753559738
----------------------------------------------

file name : 65+64_63+108_40+108_68_63+.csv
Rules(classes) number : 4
Words(features) number : 3
Records number : 252

   rule   weight word1  word2    word3
0     0  0.25472   por  haber  adoptar
1     1  0.25472   por  haber  adoptar
2     2  0.24528   por  haber  adoptar
3     3  0.24528   por  haber  adoptar

model : NaiveBayes , score = 0.1854522284236849
model : LinearSVM , score = 0.20280748827570969
model : RBFSVM , score = 0.2596570585636813
model : DecisionTree , score = 0.12557739997430464
model : RandomForest , score = 0.09485241605291463
model : AdaBoost , score = 0.1167580398440067
----------------------------------------------

file name : 7+8+9+10_108_1+11_108_1+33_1_108_1+.csv
Rules(classes) number : 6
Words(features) number : 4
Records number : 48480

   rule    weight word1    word2 word3   word4
0     0  0.150565    el  periodo    de  sesión
1     1  0.201926    el  periodo    de  sesión
2     2  0.206313    el  periodo    de  sesión
3     3  0.150565    el  periodo    de  sesión
4     4  0.140065    el  periodo    de  sesión
5     5  0.150565    el  periodo    de  sesión

model : NaiveBayes , score = 0.16419735349154174
model : LinearSVM , score = 0.1661864935934602
model : RBFSVM , score = 0.1609621342969151
model : DecisionTree , score = 0.15462650678497822
model : RandomForest , score = 0.15304989039368436
model : AdaBoost , score = 0.14956443099905853
----------------------------------------------

file name : 25+26_1+16_106_29_1+10_29_106_29_1+11_29_106_29_1+33_23+33_24_1+33_14_106_29_1+33_1_29_106_29_1+.csv
Rules(classes) number : 9
Words(features) number : 6
Records number : 72

   rule    weight word1     word2    word3 word4  word5   word6
0     0  0.118151    el  comisión  europeo     y  vario  estado
1     1  0.105356    el  comisión  europeo     y  vario  estado
2     2  0.118151    el  comisión  europeo     y  vario  estado
3     3  0.106344    el  comisión  europeo     y  vario  estado
4     4  0.103996    el  comisión  europeo     y  vario  estado
5     5  0.118151    el  comisión  europeo     y  vario  estado
6     6  0.105356    el  comisión  europeo     y  vario  estado
7     7  0.118151    el  comisión  europeo     y  vario  estado
8     8  0.106344    el  comisión  europeo     y  vario  estado

model : NaiveBayes , score = 0.029696334364774767
model : LinearSVM , score = 0.11456630699260187
model : RBFSVM , score = 0.11456630699260187
model : DecisionTree , score = 0.029696334364774767
model : RandomForest , score = 0.029696334364774767
model : AdaBoost , score = 0.026728736800260753
----------------------------------------------

file name : 79+84_63+100_42+100_47_63+.csv
Rules(classes) number : 4
Words(features) number : 4
Records number : 252

   rule    weight word1 word2  word3  word4
0     0  0.296603    no    lo  haber  hacer
1     1  0.224577    no    lo  haber  hacer
2     2  0.249630    no    lo  haber  hacer
3     3  0.229190    no    lo  haber  hacer

model : NaiveBayes , score = 0.21821112734051148
model : LinearSVM , score = 0.2624706289668316
model : RBFSVM , score = 0.2703155070734252
model : DecisionTree , score = 0.18376902613505058
model : RandomForest , score = 0.13061732329930537
model : AdaBoost , score = 0.13723675459618487
----------------------------------------------

file name : 21+10_30+10_110_29+11_30+11_110_29+33_1_30+33_1_110_29+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 2625

   rule    weight word1   word2 word3     word4
0     0  0.153290   uno  medida   muy  concreto
1     1  0.139238   uno  medida   muy  concreto
2     2  0.139238   uno  medida   muy  concreto
3     3  0.144879   uno  medida   muy  concreto
4     4  0.144879   uno  medida   muy  concreto
5     5  0.139238   uno  medida   muy  concreto
6     6  0.139238   uno  medida   muy  concreto

model : NaiveBayes , score = 0.13412142502798866
model : LinearSVM , score = 0.1353239599793647
model : RBFSVM , score = 0.1511010967722058
model : DecisionTree , score = 0.12110940368235748
model : RandomForest , score = 0.09958795356372663
model : AdaBoost , score = 0.0963204974632738
----------------------------------------------

file name : 30+110_29+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 2330

   rule  weight word1    word2
0     0     0.5   muy  diverso
1     1     0.5   muy  diverso

model : NaiveBayes , score = 0.4861290996488517
model : LinearSVM , score = 0.4869539176571576
model : RBFSVM , score = 0.3770546423512336
model : DecisionTree , score = 0.45048994630836775
model : RandomForest , score = 0.44570368285343176
model : AdaBoost , score = 0.4438495914597549
----------------------------------------------

file name : 64+91+108_68+.csv
Rules(classes) number : 3
Words(features) number : 2
Records number : 8310

   rule    weight word1     word2
0     0  0.333705    de  examinar
1     1  0.334584    de  examinar
2     2  0.331712    de  examinar

model : NaiveBayes , score = 0.33265543433716654
model : LinearSVM , score = 0.3397881270396379
model : RBFSVM , score = 0.24434363205564905
model : DecisionTree , score = 0.3232987533102557
model : RandomForest , score = 0.30205680231298204
model : AdaBoost , score = 0.3089100161490987
----------------------------------------------

file name : 84+100_47+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 478

   rule  weight    word1 word2  word3
0     0     0.5  también    lo  poner
1     1     0.5  también    lo  poner

model : NaiveBayes , score = 0.5010828716535284
model : LinearSVM , score = 0.4840620915843279
model : RBFSVM , score = 0.34143532748351807
model : DecisionTree , score = 0.40254761567725456
model : RandomForest , score = 0.4106106872301484
model : AdaBoost , score = 0.4203780289178144
----------------------------------------------

file name : 64_64+64_108_68+91_64+91_108_68+108_38+108_68_64+108_68_108_68+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 14

   rule    weight word1   word2 word3    word4
0     0  0.141119    de  llegar     a  cumplir
1     1  0.141119    de  llegar     a  cumplir
2     2  0.142141    de  llegar     a  cumplir
3     3  0.142141    de  llegar     a  cumplir
4     4  0.151996    de  llegar     a  cumplir
5     5  0.140742    de  llegar     a  cumplir
6     6  0.140742    de  llegar     a  cumplir

model : NaiveBayes , score = 0.141119
model : LinearSVM , score = 0.151996
model : RBFSVM , score = 0.151996
model : DecisionTree , score = 0.151996
model : RandomForest , score = 0.140742
model : AdaBoost , score = 0.151996
----------------------------------------------

file name : 42+45_63+47_63+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 21

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1  word2    word3
0     0  0.348117    lo  haber  aprobar
1     1  0.315264    lo  haber  aprobar
2     2  0.336619    lo  haber  aprobar

model : NaiveBayes , score = 0.16708374376704985
model : LinearSVM , score = 0.2792618308656347
model : RBFSVM , score = 0.2792618308656347
model : DecisionTree , score = 0.07951611775934861
model : RandomForest , score = 0.07951611775934861
model : AdaBoost , score = 0.07951611775934861
----------------------------------------------

file name : 16+10_29+11_29+33_14+33_1_29+.csv
Rules(classes) number : 5
Words(features) number : 3
Records number : 114920

   rule    weight word1     word2       word3
0     0  0.209393    el  servicio  competente
1     1  0.194581    el  servicio  competente
2     2  0.192052    el  servicio  competente
3     3  0.209393    el  servicio  competente
4     4  0.194581    el  servicio  competente

model : NaiveBayes , score = 0.20713068788495195
model : LinearSVM , score = 0.20767887864006607
model : RBFSVM , score = 0.19787543551643047
model : DecisionTree , score = 0.20371064322425628
model : RandomForest , score = 0.1997277746914184
model : AdaBoost , score = 0.20114442854828196
----------------------------------------------

file name : 92+100_68+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 380

   rule    weight word1  word2
0     0  0.505715    no  crear
1     1  0.494285    no  crear

model : NaiveBayes , score = 0.4600878205646209
model : LinearSVM , score = 0.46085152158880804
model : RBFSVM , score = 0.33494255798491407
model : DecisionTree , score = 0.41368250856415995
model : RandomForest , score = 0.37487519219381
model : AdaBoost , score = 0.4063428873583521
----------------------------------------------

file name : 26+16_106_29+10_29_106_29+11_29_106_29+33_24+33_14_106_29+33_1_29_106_29+.csv
Rules(classes) number : 7
Words(features) number : 5
Records number : 4116

   rule    weight word1       word2    word3 word4       word5
0     0  0.167642    el  desarrollo  técnico     y  industrial
1     1  0.138759    el  desarrollo  técnico     y  industrial
2     2  0.128489    el  desarrollo  técnico     y  industrial
3     3  0.130220    el  desarrollo  técnico     y  industrial
4     4  0.167642    el  desarrollo  técnico     y  industrial
5     5  0.138759    el  desarrollo  técnico     y  industrial
6     6  0.128489    el  desarrollo  técnico     y  industrial

model : NaiveBayes , score = 0.12281064387846821
model : LinearSVM , score = 0.12810103192443603
model : RBFSVM , score = 0.14976190134123576
model : DecisionTree , score = 0.1090782088471264
model : RandomForest , score = 0.0975205407192285
model : AdaBoost , score = 0.10507606742700715
----------------------------------------------

file name : 76_64+76_108_68+75_38+75_67+75_63_64+75_63_108_68+100_39+100_40_64+100_40_108_68+100_37_38+100_37_67+100_37_63_64+100_37_63_108_68+.csv
Rules(classes) number : 13
Words(features) number : 5
Records number : 26

    rule    weight        word1  word2   word3 word4    word5
0      0  0.076446  ni_siquiera  haber  llegar     a  emplear
1      1  0.076446  ni_siquiera  haber  llegar     a  emplear
2      2  0.078513  ni_siquiera  haber  llegar     a  emplear
3      3  0.076446  ni_siquiera  haber  llegar     a  emplear
4      4  0.076446  ni_siquiera  haber  llegar     a  emplear
5      5  0.076446  ni_siquiera  haber  llegar     a  emplear
6      6  0.078513  ni_siquiera  haber  llegar     a  emplear
7      7  0.076446  ni_siquiera  haber  llegar     a  emplear
8      8  0.076446  ni_siquiera  haber  llegar     a  emplear
9      9  0.078513  ni_siquiera  haber  llegar     a  emplear
10    10  0.076446  ni_siquiera  haber  llegar     a  emplear
11    11  0.076446  ni_siquiera  haber  llegar     a  emplear
12    12  0.076446  ni_siquiera  haber  llegar     a  emplear

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.07707142653346746
model : RBFSVM , score = 0.07707142653346746
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 20_106+12_29_106+113_24+113_14_106+113_1_29_106+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 25

   rule    weight word1       word2     word3 word4
0     0  0.203738   dos  comentario  sencillo     y
1     1  0.196612   dos  comentario  sencillo     y
2     2  0.199300   dos  comentario  sencillo     y
3     3  0.203738   dos  comentario  sencillo     y
4     4  0.196612   dos  comentario  sencillo     y

model : NaiveBayes , score = 0.07628991346706404
model : LinearSVM , score = 0.15087718345207474
model : RBFSVM , score = 0.15087718345207474
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 30_64+30_108_68+110_67+110_63_64+110_63_108_68+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 35

   rule    weight word1     word2 word3   word4
0     0  0.204084  bien  informar  para  evitar
1     1  0.193874  bien  informar  para  evitar
2     2  0.204084  bien  informar  para  evitar
3     3  0.204084  bien  informar  para  evitar
4     4  0.193874  bien  informar  para  evitar

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.1692041208560311
model : RBFSVM , score = 0.1692041208560311
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 80+108_92+108_100_68+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 63

   rule    weight word1 word2   word3
0     0  0.340001  para    no  volver
1     1  0.334441  para    no  volver
2     2  0.325558  para    no  volver

model : NaiveBayes , score = 0.21988317710465202
model : LinearSVM , score = 0.2792714064114462
model : RBFSVM , score = 0.3038233460112918
model : DecisionTree , score = 0.15838051390647628
model : RandomForest , score = 0.12615808996952854
model : AdaBoost , score = 0.12480093199720507
----------------------------------------------

file name : 97+108_98+108_33_99+108_33_113_108_1+.csv
Rules(classes) number : 4
Words(features) number : 5
Records number : 264

   rule    weight     word1 word2  word3 word4  word5
0     0  0.257936  antes_de    el      1    de  enero
1     1  0.251593  antes_de    el      1    de  enero
2     2  0.251621  antes_de    el      1    de  enero
3     3  0.238850  antes_de    el      1    de  enero

model : NaiveBayes , score = 0.18412234779307454
model : LinearSVM , score = 0.1712634434048582
model : RBFSVM , score = 0.2665445350564511
model : DecisionTree , score = 0.09966666528424266
model : RandomForest , score = 0.0893498872653412
model : AdaBoost , score = 0.12985147953020063
----------------------------------------------

file name : 42_64+42_108_68+47_67+47_63_64+47_63_108_68+.csv
Rules(classes) number : 5
Words(features) number : 5
Records number : 15

   rule    weight word1  word2  word3 word4     word5
0     0  0.202631    lo  haber  hacer   sin  informar
1     1  0.200782    lo  haber  hacer   sin  informar
2     2  0.199458    lo  haber  hacer   sin  informar
3     3  0.199458    lo  haber  hacer   sin  informar
4     4  0.197671    lo  haber  hacer   sin  informar

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.13698720732322098
model : RBFSVM , score = 0.13698720732322098
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 30+110_63+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 484

   rule  weight word1    word2
0     0     0.5  bien  adaptar
1     1     0.5  bien  adaptar

model : NaiveBayes , score = 0.4630506070154525
model : LinearSVM , score = 0.4630506070154525
model : RBFSVM , score = 0.32572428366113676
model : DecisionTree , score = 0.4001060386298835
model : RandomForest , score = 0.38451515996862545
model : AdaBoost , score = 0.3845365323262198
----------------------------------------------

file name : 98_29+33_99_29+33_113_108_14+33_113_108_1_29+.csv
Rules(classes) number : 4
Words(features) number : 5
Records number : 12

   rule    weight word1  word2 word3  word4   word5
0     0  0.288897    el      3    de  marzo  pasado
1     1  0.258390    el      3    de  marzo  pasado
2     2  0.227527    el      3    de  marzo  pasado
3     3  0.225187    el      3    de  marzo  pasado

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.15216143917608507
model : RBFSVM , score = 0.15216143917608507
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 35+37+.csv
Rules(classes) number : 2
Words(features) number : 1
Records number : 1222

   rule    weight word1
0     0  0.507778   hay
1     1  0.492222   hay

model : NaiveBayes , score = 0.5081430489169222
model : LinearSVM , score = 0.5111208491983028
model : RBFSVM , score = 0.5111208491983028
model : DecisionTree , score = 0.5111208491983028
model : RandomForest , score = 0.5111208491983028
model : AdaBoost , score = 0.5111208491983028
----------------------------------------------

file name : 17_63_29+31_15+31_1_63_29+33_29_15+33_29_1_63_29+.csv
Rules(classes) number : 5
Words(features) number : 5
Records number : 10

   rule    weight word1     word2     word3    word4     word5
0     0  0.201255    el  numeroso  decisión  aprobar  relativo
1     1  0.198118    el  numeroso  decisión  aprobar  relativo
2     2  0.201255    el  numeroso  decisión  aprobar  relativo
3     3  0.198118    el  numeroso  decisión  aprobar  relativo
4     4  0.201255    el  numeroso  decisión  aprobar  relativo

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.19984007429839853
model : RBFSVM , score = 0.19984007429839853
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 20+12_29+113_14+113_1_29+.csv
Rules(classes) number : 4
Words(features) number : 3
Records number : 1100

   rule    weight word1     word2      word3
0     0  0.282894  tres  objetivo  principal
1     1  0.217106  tres  objetivo  principal
2     2  0.282894  tres  objetivo  principal
3     3  0.217106  tres  objetivo  principal

model : NaiveBayes , score = 0.23407372214880567
model : LinearSVM , score = 0.24638366234420286
model : RBFSVM , score = 0.2604208440404019
model : DecisionTree , score = 0.21305397542331572
model : RandomForest , score = 0.12586922004458254
model : AdaBoost , score = 0.1717893312984715
----------------------------------------------

file name : 65_64+65_108_68+64_67+64_63_64+64_63_108_68+108_40_64+108_40_108_68+108_68_67+108_68_63_64+108_68_63_108_68+.csv
Rules(classes) number : 10
Words(features) number : 5
Records number : 20

   rule    weight     word1  word2     word3 word4  word5
0     0  0.099691  antes_de  haber  aprender     a  andar
1     1  0.099691  antes_de  haber  aprender     a  andar
2     2  0.099691  antes_de  haber  aprender     a  andar
3     3  0.099691  antes_de  haber  aprender     a  andar
4     4  0.099691  antes_de  haber  aprender     a  andar
5     5  0.100309  antes_de  haber  aprender     a  andar
6     6  0.100309  antes_de  haber  aprender     a  andar
7     7  0.100309  antes_de  haber  aprender     a  andar
8     8  0.100309  antes_de  haber  aprender     a  andar
9     9  0.100309  antes_de  haber  aprender     a  andar

model : NaiveBayes , score = 0.09969110030889967
model : LinearSVM , score = 0.10030889969110031
model : RBFSVM , score = 0.10030889969110031
model : DecisionTree , score = 0.10030889969110031
model : RandomForest , score = 0.09969110030889967
model : AdaBoost , score = 0.10030889969110031
----------------------------------------------

file name : 74+75+100_35+100_37+.csv
Rules(classes) number : 4
Words(features) number : 2
Records number : 1836

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1 word2
0     0  0.287918    no   hay
1     1  0.221473    no   hay
2     2  0.261190    no   hay
3     3  0.229420    no   hay

model : NaiveBayes , score = 0.222433076533358
model : LinearSVM , score = 0.24922576304028074
model : RBFSVM , score = 0.23637689663456252
model : DecisionTree , score = 0.22220220609108216
model : RandomForest , score = 0.21600669587384547
model : AdaBoost , score = 0.22307305648417208
----------------------------------------------

file name : 40+35_63+37_63+.csv
Rules(classes) number : 3
Words(features) number : 2
Records number : 924

   rule    weight  word1     word2
0     0  0.333450  haber  convenir
1     1  0.333099  haber  convenir
2     2  0.333450  haber  convenir

model : NaiveBayes , score = 0.33343316386434263
model : LinearSVM , score = 0.346860081569324
model : RBFSVM , score = 0.22955782483687012
model : DecisionTree , score = 0.29952160210106243
model : RandomForest , score = 0.26062750522115874
model : AdaBoost , score = 0.2539933509453858
----------------------------------------------

file name : 25_29+26_14+26_1_29+16_106_29_14+16_106_29_1_29+10_29_106_29_14+10_29_106_29_1_29+11_29_106_29_14+11_29_106_29_1_29+33_23_29+33_24_14+33_24_1_29+33_14_106_29_14+33_14_106_29_1_29+33_1_29_106_29_14+33_1_29_106_29_1_29+.csv
Rules(classes) number : 16
Words(features) number : 7
Records number : 32

,rule,weight,word1,word2,word3,word4,word5,word6,word7
0,0,0.063607,el,derecho,humano,y,vario,acontecimiento,reciente
1,1,0.061555,el,derecho,humano,y,vario,acontecimiento,reciente
2,2,0.058596,el,derecho,humano,y,vario,acontecimiento,reciente
3,3,0.066319,el,derecho,humano,y,vario,acontecimiento,reciente
4,4,0.063607,el,derecho,humano,y,vario,acontecimiento,reciente
5,5,0.063693,el,derecho,humano,y,vario,acontecimiento,reciente
6,6,0.061188,el,derecho,humano,y,vario,acontecimiento,reciente
7,7,0.062647,el,derecho,humano,y,vario,acontecimiento,reciente
8,8,0.060222,el,derecho,humano,y,vario,acontecimiento,reciente
9,9,0.063607,el,derecho,humano,y,vario,acontecimiento,reciente
10,10,0.061555,el,derecho,humano,y,vario,acontecimiento,reciente
11,11,0.058596,el,derecho,humano,y,vario,acontecimiento,reciente
12,12,0.066319,el,derecho,humano,y,vario,acontecimiento,reciente
13,13,0.063607,el,derecho,humano,y,vario,acontecimiento,reciente
14,14,0.063693,el,derecho,humano,y,vario,acontecimiento,reciente
15,15,0.061188,el,derecho,humano,y,vario,acontecimiento,reciente

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.06659291686619512
model : RBFSVM , score = 0.06659291686619512
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 76+74_63+75_63+100_40+100_35_63+100_37_63+.csv
Rules(classes) number : 6
Words(features) number : 3
Records number : 618

   rule   weight  word1  word2   word3
0     0  0.17124  quizá  haber  llegar
1     1  0.15752  quizá  haber  llegar
2     2  0.17124  quizá  haber  llegar
3     3  0.17124  quizá  haber  llegar
4     4  0.15752  quizá  haber  llegar
5     5  0.17124  quizá  haber  llegar

model : NaiveBayes , score = 0.15541247961251903
model : LinearSVM , score = 0.15642422260752123
model : RBFSVM , score = 0.1781171815647689
model : DecisionTree , score = 0.11920340132556226
model : RandomForest , score = 0.07302332395743687
model : AdaBoost , score = 0.08910207760680809
----------------------------------------------

file name : 19+16_29+10_29_29+11_29_29+33_15+33_14_29+33_1_29_29+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 6734

   rule    weight    word1      word2     word3 word4
0     0  0.146545  ninguno  obstáculo  jurídico  real
1     1  0.140010  ninguno  obstáculo  jurídico  real
2     2  0.143535  ninguno  obstáculo  jurídico  real
3     3  0.139819  ninguno  obstáculo  jurídico  real
4     4  0.146545  ninguno  obstáculo  jurídico  real
5     5  0.140010  ninguno  obstáculo  jurídico  real
6     6  0.143535  ninguno  obstáculo  jurídico  real

model : NaiveBayes , score = 0.13357139094346357
model : LinearSVM , score = 0.14457829516012763
model : RBFSVM , score = 0.14829315087623948
model : DecisionTree , score = 0.1286554919938203
model : RandomForest , score = 0.09791982020184645
model : AdaBoost , score = 0.10583255654691229
----------------------------------------------

file name : 93+100_69+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 14

   rule    weight word1  word2
0     0  0.503313    no  hacer
1     1  0.496687    no  hacer

model : NaiveBayes , score = 0.28706249003625595
model : LinearSVM , score = 0.4242505909801415
model : RBFSVM , score = 0.4242505909801415
model : DecisionTree , score = 0.2855692474154155
model : RandomForest , score = 0.28331284259950834
model : AdaBoost , score = 0.2855692474154155
----------------------------------------------

file name : 28+16_106_30+16_106_100_29+10_29_106_30+10_29_106_100_29+11_29_106_30+11_29_106_100_29+33_14_106_30+33_14_106_100_29+33_1_29_106_30+33_1_29_106_100_29+.csv
Rules(classes) number : 11
Words(features) number : 6
Records number : 242

    rule    weight word1   word2    word3 word4      word5     word6
0      0  0.091505   uno  debate  abierto     y  mucho_más  dinámico
1      1  0.092972   uno  debate  abierto     y  mucho_más  dinámico
2      2  0.092972   uno  debate  abierto     y  mucho_más  dinámico
3      3  0.089077   uno  debate  abierto     y  mucho_más  dinámico
4      4  0.089077   uno  debate  abierto     y  mucho_más  dinámico
5      5  0.090149   uno  debate  abierto     y  mucho_más  dinámico
6      6  0.090149   uno  debate  abierto     y  mucho_más  dinámico
7      7  0.092972   uno  debate  abierto     y  mucho_más  dinámico
8      8  0.092972   uno  debate  abierto     y  mucho_más  dinámico
9      9  0.089077   uno  debate  abierto     y  mucho_más  dinámico
10    10  0.089077   uno  debate  abierto     y  mucho_más  dinámico

model : NaiveBayes , score = 0.02499643012919274
model : LinearSVM , score = 0.05853263185872462
model : RBFSVM , score = 0.09487956768291234
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.04976535493069682
----------------------------------------------

file name : 40+63_63+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 4

   rule    weight  word1    word2
0     0  0.486204  haber  repetir
1     1  0.513796  haber  repetir

model : NaiveBayes , score = 0.48620399999999997
model : LinearSVM , score = 0.513796
model : RBFSVM , score = 0.513796
model : DecisionTree , score = 0.513796
model : RandomForest , score = 0.513796
model : AdaBoost , score = 0.513796
----------------------------------------------

file name : 98+33_99+33_113_108_1+.csv
Rules(classes) number : 3
Words(features) number : 4
Records number : 213

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1 word2 word3  word4
0     0  0.336429    el    27    de  marzo
1     1  0.338076    el    27    de  marzo
2     2  0.325496    el    27    de  marzo

model : NaiveBayes , score = 0.2851337068878107
model : LinearSVM , score = 0.26689440142665044
model : RBFSVM , score = 0.32354741596092174
model : DecisionTree , score = 0.130059015477188
model : RandomForest , score = 0.13016797136447059
model : AdaBoost , score = 0.17396683289488685
----------------------------------------------

file name : 40+37_63+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 11700

   rule  weight  word1    word2
0     0     0.5  haber  incluir
1     1     0.5  haber  incluir

model : NaiveBayes , score = 0.4917035327565232
model : LinearSVM , score = 0.4933275214113945
model : RBFSVM , score = 0.43242836955937985
model : DecisionTree , score = 0.4761490467706863
model : RandomForest , score = 0.47036086996205184
model : AdaBoost , score = 0.46738221547011866
----------------------------------------------

file name : 75+100_37+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 23248

   rule    weight word1     word2
0     0  0.515855    no  respetar
1     1  0.484145    no  respetar

model : NaiveBayes , score = 0.5018283420998348
model : LinearSVM , score = 0.5043203550155587
model : RBFSVM , score = 0.41599039176105
model : DecisionTree , score = 0.49078794172529744
model : RandomForest , score = 0.4824725030459211
model : AdaBoost , score = 0.48468805774189694
----------------------------------------------

file name : 20+12_29+113_15+113_14+113_1_29+.csv
Rules(classes) number : 5
Words(features) number : 3
Records number : 45

   rule    weight   word1 word2     word3
0     0  0.200115  20.000  acto  jurídico
1     1  0.200115  20.000  acto  jurídico
2     2  0.199540  20.000  acto  jurídico
3     3  0.200115  20.000  acto  jurídico
4     4  0.200115  20.000  acto  jurídico

model : NaiveBayes , score = 0.1309606202361131
model : LinearSVM , score = 0.1751275346500531
model : RBFSVM , score = 0.1751275346500531
model : DecisionTree , score = 0.04407809457336834
model : RandomForest , score = 0.04407809457336834
model : AdaBoost , score = 0.04407809457336834
----------------------------------------------

file name : 17+31_1+33_29_1+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 20829

   rule    weight word1  word2    word3
0     0  0.333333   uno  bueno  fórmula
1     1  0.333333   uno  bueno  fórmula
2     2  0.333333   uno  bueno  fórmula

model : NaiveBayes , score = 0.3295921616760996
model : LinearSVM , score = 0.32920708495257434
model : RBFSVM , score = 0.14985848799535995
model : DecisionTree , score = 0.3181969882034842
model : RandomForest , score = 0.3066639449713755
model : AdaBoost , score = 0.30670845232364624
----------------------------------------------

file name : 32+33_30+33_100_63+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 51

   rule    weight word1 word2      word3
0     0  0.336110    el   más  preocupar
1     1  0.331945    el   más  preocupar
2     2  0.331945    el   más  preocupar

model : NaiveBayes , score = 0.2300763669196149
model : LinearSVM , score = 0.30457753516806924
model : RBFSVM , score = 0.30457753516806924
model : DecisionTree , score = 0.15145278645061538
model : RandomForest , score = 0.1906317271927346
model : AdaBoost , score = 0.18972779925884573
----------------------------------------------

file name : 76_64+76_108_68+74_67+74_63_64+74_63_108_68+75_67+75_63_64+75_63_108_68+100_40_64+100_40_108_68+100_35_67+100_35_63_64+100_35_63_108_68+100_37_67+100_37_63_64+100_37_63_108_68+.csv
Rules(classes) number : 16
Words(features) number : 5
Records number : 32

    rule    weight        word1  word2    word3 word4     word5
0      0  0.066377  ni_siquiera  haber  empezar     a  trabajar
1      1  0.066377  ni_siquiera  haber  empezar     a  trabajar
2      2  0.056037  ni_siquiera  haber  empezar     a  trabajar
3      3  0.056037  ni_siquiera  haber  empezar     a  trabajar
4      4  0.056037  ni_siquiera  haber  empezar     a  trabajar
5      5  0.066377  ni_siquiera  haber  empezar     a  trabajar
6      6  0.066377  ni_siquiera  haber  empezar     a  trabajar
7      7  0.066377  ni_siquiera  haber  empezar     a  trabajar
8      8  0.066377  ni_siquiera  haber  empezar     a  trabajar
9      9  0.066377  ni_siquiera  haber  empezar     a  trabajar
10    10  0.056037  ni_siquiera  haber  empezar     a  trabajar
11    11  0.056037  ni_siquiera  haber  empezar     a  trabajar
12    12  0.056037  ni_siquiera  haber  empezar     a  trabajar
13    13  0.066377  ni_siquiera  haber  empezar     a  trabajar
14    14  0.066377  ni_siquiera  haber  empezar     a  trabajar
15    15  0.066377  ni_siquiera  haber  empezar     a  trabajar

model : NaiveBayes , score = 0.06637753982652389
model : LinearSVM , score = 0.06637753982652389
model : RBFSVM , score = 0.06637753982652389
model : DecisionTree , score = 0.06637753982652389
model : RandomForest , score = 0.06637753982652389
model : AdaBoost , score = 0.06637753982652389
----------------------------------------------

file name : 30_64+30_108_68+100_67+100_63_64+100_63_108_68+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 105

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule  weight      word1     word2 word3   word4
0     0     0.2  realmente  disponer     a  librar
1     1     0.2  realmente  disponer     a  librar
2     2     0.2  realmente  disponer     a  librar
3     3     0.2  realmente  disponer     a  librar
4     4     0.2  realmente  disponer     a  librar

model : NaiveBayes , score = 0.1131868758808217
model : LinearSVM , score = 0.18936578010447513
model : RBFSVM , score = 0.18913502781145083
model : DecisionTree , score = 0.05658834573615122
model : RandomForest , score = 0.018868314183344823
model : AdaBoost , score = 0.07544836151255443
----------------------------------------------

file name : 64+108_68+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 10714

   rule    weight word1       word2
0     0  0.516806   por  considerar
1     1  0.483194   por  considerar

model : NaiveBayes , score = 0.4929621418967288
model : LinearSVM , score = 0.4942816164223336
model : RBFSVM , score = 0.37833582985460873
model : DecisionTree , score = 0.4755386350131668
model : RandomForest , score = 0.47136806950311533
model : AdaBoost , score = 0.4797982398098202
----------------------------------------------

file name : 45+47+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 6

   rule    weight word1  word2
0     0  0.467616    lo  haber
1     1  0.532384    lo  haber

model : NaiveBayes , score = 0.6510258814294746
model : LinearSVM , score = 0.3489741185705253
model : RBFSVM , score = 0.3489741185705253
model : DecisionTree , score = 0.3489741185705253
model : RandomForest , score = 0.3489741185705253
model : AdaBoost , score = 0.3489741185705253
----------------------------------------------

file name : 38+69_64+69_108_68+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 6

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: divide by zero encountered in true_divide
  (self.sigma_[i, :]), 1)
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight   word1 word2 word3
0     0  0.349408  llegar     a   ser
1     1  0.325296  llegar     a   ser
2     2  0.325296  llegar     a   ser

model : NaiveBayes , score = 0.349408
model : LinearSVM , score = 0.349408
model : RBFSVM , score = 0.349408
model : DecisionTree , score = 0.349408
model : RandomForest , score = 0.349408
model : AdaBoost , score = 0.349408
----------------------------------------------

file name : 65+64_63+91_63+108_40+108_68_63+.csv
Rules(classes) number : 5
Words(features) number : 3
Records number : 90

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1  word2 word3
0     0  0.198241    de  haber   ser
1     1  0.201699    de  haber   ser
2     2  0.202473    de  haber   ser
3     3  0.198794    de  haber   ser
4     4  0.198794    de  haber   ser

model : NaiveBayes , score = 0.15721598781487842
model : LinearSVM , score = 0.13246373705958808
model : RBFSVM , score = 0.20180785092965567
model : DecisionTree , score = 0.04382684750214566
model : RandomForest , score = 0.021909366934298014
model : AdaBoost , score = 0.08857531485899726
----------------------------------------------

file name : 40_64+40_108_68+35_67+35_63_64+35_63_108_68+37_67+37_63_64+37_63_108_68+.csv
Rules(classes) number : 8
Words(features) number : 4
Records number : 16

   rule    weight  word1     word2 word3     word4
0     0  0.133838  haber  amenazar   con  recurrir
1     1  0.130860  haber  amenazar   con  recurrir
2     2  0.112964  haber  amenazar   con  recurrir
3     3  0.112964  haber  amenazar   con  recurrir
4     4  0.110838  haber  amenazar   con  recurrir
5     5  0.133838  haber  amenazar   con  recurrir
6     6  0.133838  haber  amenazar   con  recurrir
7     7  0.130860  haber  amenazar   con  recurrir

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.1264077214410737
model : RBFSVM , score = 0.1264077214410737
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 7_63_106_29+8_63_106_29+9_63_106_29+10_108_24+10_108_1_63_106_29+11_108_24+11_108_1_63_106_29+33_1_108_24+33_1_108_1_63_106_29+.csv
Rules(classes) number : 9
Words(features) number : 7
Records number : 45

   rule    weight word1       word2 word3      word4    word5 word6    word7
0     0  0.111574   uno  definición    de  ciudadano  ampliar     y  confuso
1     1  0.110444   uno  definición    de  ciudadano  ampliar     y  confuso
2     2  0.111013   uno  definición    de  ciudadano  ampliar     y  confuso
3     3  0.111046   uno  definición    de  ciudadano  ampliar     y  confuso
4     4  0.111574   uno  definición    de  ciudadano  ampliar     y  confuso
5     5  0.110600   uno  definición    de  ciudadano  ampliar     y  confuso
6     6  0.111129   uno  definición    de  ciudadano  ampliar     y  confuso
7     7  0.111046   uno  definición    de  ciudadano  ampliar     y  confuso
8     8  0.111574   uno  definición    de  ciudadano  ampliar     y  confuso

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.08862622990678397
model : RBFSVM , score = 0.08862622990678397
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 76+75_63+100_40+100_37_63+.csv
Rules(classes) number : 4
Words(features) number : 3
Records number : 5892

   rule    weight word1  word2    word3
0     0  0.256020    no  haber  mejorar
1     1  0.247588    no  haber  mejorar
2     2  0.248196    no  haber  mejorar
3     3  0.248196    no  haber  mejorar

model : NaiveBayes , score = 0.25182717265680205
model : LinearSVM , score = 0.248560018366495
model : RBFSVM , score = 0.2392588726742863
model : DecisionTree , score = 0.22779809088144265
model : RandomForest , score = 0.1955185463236218
model : AdaBoost , score = 0.21712035680478434
----------------------------------------------

file name : 14+1_29+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 12718

   rule    weight  word1         word2
0     0  0.512582  forma  transparente
1     1  0.487418  forma  transparente

model : NaiveBayes , score = 0.5107458466229141
model : LinearSVM , score = 0.5118126996132488
model : RBFSVM , score = 0.3961875644243543
model : DecisionTree , score = 0.49368570571413434
model : RandomForest , score = 0.48852175500059875
model : AdaBoost , score = 0.4863975090871166
----------------------------------------------

file name : 7_29_106_29+8_29_106_29+9_29_106_29+10_108_24+10_108_14_106_29+10_108_1_29_106_29+11_108_24+11_108_14_106_29+11_108_1_29_106_29+33_1_108_24+33_1_108_14_106_29+33_1_108_1_29_106_29+.csv
Rules(classes) number : 12
Words(features) number : 7
Records number : 960

    rule    weight word1     word2 word3   word4      word5 word6      word7
0      0  0.085027    el  comisión    de  asunto  económico     y  monetario
1      1  0.084131    el  comisión    de  asunto  económico     y  monetario
2      2  0.083727    el  comisión    de  asunto  económico     y  monetario
3      3  0.086464    el  comisión    de  asunto  económico     y  monetario
4      4  0.079889    el  comisión    de  asunto  económico     y  monetario
5      5  0.085027    el  comisión    de  asunto  económico     y  monetario
6      6  0.083974    el  comisión    de  asunto  económico     y  monetario
7      7  0.077760    el  comisión    de  asunto  económico     y  monetario
8      8  0.082619    el  comisión    de  asunto  económico     y  monetario
9      9  0.086464    el  comisión    de  asunto  económico     y  monetario
10    10  0.079889    el  comisión    de  asunto  económico     y  monetario
11    11  0.085027    el  comisión    de  asunto  económico     y  monetario

model : NaiveBayes , score = 0.07544499220507477
model : LinearSVM , score = 0.052612650939349755
model : RBFSVM , score = 0.08680020851121312
model : DecisionTree , score = 0.017581560870878046
model : RandomForest , score = 0.01424467609890829
model : AdaBoost , score = 0.03310003280258349
----------------------------------------------

file name : 18+17_29+31_15+31_14+31_1_29+33_29_15+33_29_14+33_29_1_29+.csv
Rules(classes) number : 8
Words(features) number : 4
Records number : 264

   rule    weight word1  word2       word3        word4
0     0  0.126349    el  nuevo  iniciativa  comunitario
1     1  0.126684    el  nuevo  iniciativa  comunitario
2     2  0.120451    el  nuevo  iniciativa  comunitario
3     3  0.126349    el  nuevo  iniciativa  comunitario
4     4  0.126684    el  nuevo  iniciativa  comunitario
5     5  0.120451    el  nuevo  iniciativa  comunitario
6     6  0.126349    el  nuevo  iniciativa  comunitario
7     7  0.126684    el  nuevo  iniciativa  comunitario

model : NaiveBayes , score = 0.05998969026970071
model : LinearSVM , score = 0.10552628754472712
model : RBFSVM , score = 0.12329034588993983
model : DecisionTree , score = 0.00795886992053042
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.05331442712214913
----------------------------------------------

file name : 67_63+63_65+63_64_63+63_108_40+63_108_68_63+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 10

   rule    weight   word1 word2  word3     word4
0     0  0.205494  culpar   por  haber  permitir
1     1  0.205494  culpar   por  haber  permitir
2     2  0.205494  culpar   por  haber  permitir
3     3  0.191759  culpar   por  haber  permitir
4     4  0.191759  culpar   por  haber  permitir

model : NaiveBayes , score = 0.205494
model : LinearSVM , score = 0.205494
model : RBFSVM , score = 0.205494
model : DecisionTree , score = 0.205494
model : RandomForest , score = 0.205494
model : AdaBoost , score = 0.205494
----------------------------------------------

file name : 95+98_108_113+33_96+33_99_108_113+33_113_108_1_108_113+.csv
Rules(classes) number : 5
Words(features) number : 6
Records number : 310

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1  word2 word3      word4 word5  word6
0     0  0.213448    el      4    de  noviembre    de   1998
1     1  0.201655    el      4    de  noviembre    de   1998
2     2  0.205052    el      4    de  noviembre    de   1998
3     3  0.194317    el      4    de  noviembre    de   1998
4     4  0.185529    el      4    de  noviembre    de   1998

model : NaiveBayes , score = 0.14465495993573385
model : LinearSVM , score = 0.17372084213541714
model : RBFSVM , score = 0.22295327450479063
model : DecisionTree , score = 0.06054547157295547
model : RandomForest , score = 0.028428275938724212
model : AdaBoost , score = 0.12970190060199288
----------------------------------------------

file name : 30+100_29+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 5240

   rule  weight     word1  word2
0     0     0.5  a_escala  local
1     1     0.5  a_escala  local

model : NaiveBayes , score = 0.48398804800554773
model : LinearSVM , score = 0.4862776422770272
model : RBFSVM , score = 0.3250500585555513
model : DecisionTree , score = 0.465989043359402
model : RandomForest , score = 0.4394429154941928
model : AdaBoost , score = 0.45410508837298397
----------------------------------------------

file name : 28+16_106_30+16_106_110_29+10_29_106_30+10_29_106_110_29+11_29_106_30+11_29_106_110_29+33_14_106_30+33_14_106_110_29+33_1_29_106_30+33_1_29_106_110_29+.csv
Rules(classes) number : 11
Words(features) number : 6
Records number : 88

    rule    weight word1  word2     word3 word4 word5     word6
0      0  0.096350   uno  punto  concreto  pero   muy  sensible
1      1  0.092374   uno  punto  concreto  pero   muy  sensible
2      2  0.092374   uno  punto  concreto  pero   muy  sensible
3      3  0.087653   uno  punto  concreto  pero   muy  sensible
4      4  0.087653   uno  punto  concreto  pero   muy  sensible
5      5  0.091771   uno  punto  concreto  pero   muy  sensible
6      6  0.091771   uno  punto  concreto  pero   muy  sensible
7      7  0.092374   uno  punto  concreto  pero   muy  sensible
8      8  0.092374   uno  punto  concreto  pero   muy  sensible
9      9  0.087653   uno  punto  concreto  pero   muy  sensible
10    10  0.087653   uno  punto  concreto  pero   muy  sensible

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.09517323380336981
model : RBFSVM , score = 0.09517323380336981
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 10_63_106_29+11_63_106_29+33_24+33_1_63_106_29+.csv
Rules(classes) number : 4
Words(features) number : 5
Records number : 48

   rule    weight word1 word2       word3 word4        word5
0     0  0.248919   uno  modo  planificar     y  sistemático
1     1  0.252398   uno  modo  planificar     y  sistemático
2     2  0.249763   uno  modo  planificar     y  sistemático
3     3  0.248919   uno  modo  planificar     y  sistemático

model : NaiveBayes , score = 0.12742105727778924
model : LinearSVM , score = 0.2592056410137905
model : RBFSVM , score = 0.2592056410137905
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.04150894525417662
----------------------------------------------

file name : 40_65+40_64_63+40_91_63+40_108_40+40_108_68_63+35_67_63+35_63_65+35_63_64_63+35_63_91_63+35_63_108_40+35_63_108_68_63+37_67_63+37_63_65+37_63_64_63+37_63_91_63+37_63_108_40+37_63_108_68_63+.csv
Rules(classes) number : 17
Words(features) number : 5
Records number : 34

    rule    weight  word1  word2 word3  word4    word5
0      0  0.058557  haber  decir    de  haber  adoptar
1      1  0.059888  haber  decir    de  haber  adoptar
2      2  0.058393  haber  decir    de  haber  adoptar
3      3  0.057981  haber  decir    de  haber  adoptar
4      4  0.057981  haber  decir    de  haber  adoptar
5      5  0.058962  haber  decir    de  haber  adoptar
6      6  0.057254  haber  decir    de  haber  adoptar
7      7  0.058962  haber  decir    de  haber  adoptar
8      8  0.057597  haber  decir    de  haber  adoptar
9      9  0.058962  haber  decir    de  haber  adoptar
10    10  0.058962  haber  decir    de  haber  adoptar
11    11  0.059888  haber  decir    de  haber  adoptar
12    12  0.058557  haber  decir    de  haber  adoptar
13    13  0.059888  haber  decir    de  haber  adoptar
14    14  0.058393  haber  decir    de  haber  adoptar
15    15  0.059888  haber  decir    de  haber  adoptar
16    16  0.059888  haber  decir    de  haber  adoptar

model : NaiveBayes , score = 0.05855728243281527
model : LinearSVM , score = 0.0598877820336654
model : RBFSVM , score = 0.0598877820336654
model : DecisionTree , score = 0.0598877820336654
model : RandomForest , score = 0.05839268248219526
model : AdaBoost , score = 0.0598877820336654
----------------------------------------------

file name : 23_29+24_14+24_1_29+14_106_29_14+14_106_29_1_29+1_29_106_29_14+1_29_106_29_1_29+.csv
Rules(classes) number : 7
Words(features) number : 6
Records number : 14

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight      word1        word2 word3     word4      word5     word6
0     0  0.143889  reducción  obligatorio     y  opcional  propuesta  relativo
1     1  0.144008  reducción  obligatorio     y  opcional  propuesta  relativo
2     2  0.143889  reducción  obligatorio     y  opcional  propuesta  relativo
3     3  0.141088  reducción  obligatorio     y  opcional  propuesta  relativo
4     4  0.140978  reducción  obligatorio     y  opcional  propuesta  relativo
5     5  0.143134  reducción  obligatorio     y  opcional  propuesta  relativo
6     6  0.143015  reducción  obligatorio     y  opcional  propuesta  relativo

model : NaiveBayes , score = 0.1438888561111439
model : LinearSVM , score = 0.14400785599214402
model : RBFSVM , score = 0.14400785599214402
model : DecisionTree , score = 0.14400785599214402
model : RandomForest , score = 0.14400785599214402
model : AdaBoost , score = 0.14400785599214402
----------------------------------------------

file name : 10+11+33_1+.csv

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

Rules(classes) number : 3
Words(features) number : 2
Records number : 269157

   rule    weight word1     word2
0     0  0.331459    el  escalera
1     1  0.337082    el  escalera
2     2  0.331459    el  escalera

model : NaiveBayes , score = 0.3333842516772396
model : LinearSVM , score = 0.3335066744992964
model : RBFSVM , score = 0.2821422374759117
model : DecisionTree , score = 0.33131072497438363
model : RandomForest , score = 0.3289805767186921
model : AdaBoost , score = 0.3321084830109897
----------------------------------------------

file name : 76_108_52+75_63_108_52+100_40_108_52+100_37_63_108_52+.csv
Rules(classes) number : 4
Words(features) number : 6
Records number : 8

   rule  weight word1  word2    word3 word4  word5 word6
0     0    0.25    ya  haber  empezar     a  hacer    lo
1     1    0.25    ya  haber  empezar     a  hacer    lo
2     2    0.25    ya  haber  empezar     a  hacer    lo
3     3    0.25    ya  haber  empezar     a  hacer    lo

model : NaiveBayes , score = 0.25
model : LinearSVM , score = 0.25
model : RBFSVM , score = 0.25
model : DecisionTree , score = 0.25
model : RandomForest , score = 0.25
model : AdaBoost , score = 0.25
----------------------------------------------

file name : 23+24_1+14_106_29_1+1_29_106_29_1+.csv
Rules(classes) number : 4
Words(features) number : 5
Records number : 28

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight         word1      word2 word3         word4 word5
0     0  0.252352  consecuencia  económico     y  incalculable  daño
1     1  0.252352  consecuencia  económico     y  incalculable  daño
2     2  0.251366  consecuencia  económico     y  incalculable  daño
3     3  0.243930  consecuencia  económico     y  incalculable  daño

model : NaiveBayes , score = 0.06864049718985643
model : LinearSVM , score = 0.2204557855078027
model : RBFSVM , score = 0.2204557855078027
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.06763873369214851
----------------------------------------------

file name : 75_69+100_70+100_37_69+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 552

   rule    weight        word1  word2   word3
0     0  0.316646  actualmente  estar  llevar
1     1  0.366708  actualmente  estar  llevar
2     2  0.316646  actualmente  estar  llevar

model : NaiveBayes , score = 0.3127688216070106
model : LinearSVM , score = 0.3452572891939757
model : RBFSVM , score = 0.3377194914074114
model : DecisionTree , score = 0.23282676815502515
model : RandomForest , score = 0.2048260357129543
model : AdaBoost , score = 0.21022800798163122
----------------------------------------------

file name : 40+35_36+35_63+37_36+37_63+.csv
Rules(classes) number : 5
Words(features) number : 2
Records number : 10

   rule    weight  word1      word2
0     0  0.220455  haber  haber_que
1     1  0.178101  haber  haber_que
2     2  0.185300  haber  haber_que
3     3  0.195689  haber  haber_que
4     4  0.220455  haber  haber_que

model : NaiveBayes , score = 0.220455
model : LinearSVM , score = 0.220455
model : RBFSVM , score = 0.220455
model : DecisionTree , score = 0.220455
model : RandomForest , score = 0.220455
model : AdaBoost , score = 0.220455
----------------------------------------------

file name : 7_29+8_29+9_29+10_108_14+10_108_1_29+11_108_14+11_108_1_29+33_1_108_14+33_1_108_1_29+.csv
Rules(classes) number : 9
Words(features) number : 5
Records number : 15057

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1     word2 word3  word4        word5
0     0  0.110232    el  programa    de  fondo  estructural
1     1  0.113624    el  programa    de  fondo  estructural
2     2  0.112062    el  programa    de  fondo  estructural
3     3  0.110865    el  programa    de  fondo  estructural
4     4  0.110232    el  programa    de  fondo  estructural
5     5  0.111261    el  programa    de  fondo  estructural
6     6  0.110628    el  programa    de  fondo  estructural
7     7  0.110865    el  programa    de  fondo  estructural
8     8  0.110232    el  programa    de  fondo  estructural

model : NaiveBayes , score = 0.10341161383475868
model : LinearSVM , score = 0.10728662965308675
model : RBFSVM , score = 0.11419949384647897
model : DecisionTree , score = 0.09967279951894004
model : RandomForest , score = 0.08666607275524917
model : AdaBoost , score = 0.0893746415611208
----------------------------------------------

file name : 7_63_29+8_63_29+9_63_29+10_108_15+10_108_1_63_29+11_108_15+11_108_1_63_29+33_1_108_15+33_1_108_1_63_29+.csv
Rules(classes) number : 9
Words(features) number : 6
Records number : 18

   rule    weight word1     word2 word3   word4    word5     word6
0     0  0.113506    el  tribunal    de  cuenta  titular  político
1     1  0.107992    el  tribunal    de  cuenta  titular  político
2     2  0.108196    el  tribunal    de  cuenta  titular  político
3     3  0.110663    el  tribunal    de  cuenta  titular  político
4     4  0.113506    el  tribunal    de  cuenta  titular  político
5     5  0.110113    el  tribunal    de  cuenta  titular  político
6     6  0.111856    el  tribunal    de  cuenta  titular  político
7     7  0.110663    el  tribunal    de  cuenta  titular  político
8     8  0.113506    el  tribunal    de  cuenta  titular  político

model : NaiveBayes , score = 0.11350588649411349
model : LinearSVM , score = 0.11350588649411349
model : RBFSVM , score = 0.11350588649411349
model : DecisionTree , score = 0.11350588649411349
model : RandomForest , score = 0.11066288933711066
model : AdaBoost , score = 0.11350588649411349
----------------------------------------------

file name : 40_108_52+37_63_108_52+.csv
Rules(classes) number : 2
Words(features) number : 5
Records number : 6

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule  weight  word1     word2 word3   word4 word5
0     0     0.5  haber  esforzar   por  lograr    lo
1     1     0.5  haber  esforzar   por  lograr    lo

model : NaiveBayes , score = 0.3333333333333333
model : LinearSVM , score = 0.3333333333333333
model : RBFSVM , score = 0.3333333333333333
model : DecisionTree , score = 0.3333333333333333
model : RandomForest , score = 0.3333333333333333
model : AdaBoost , score = 0.3333333333333333
----------------------------------------------

file name : 75_108_52+100_37_108_52+.csv
Rules(classes) number : 2
Words(features) number : 5
Records number : 4

   rule    weight word1   word2 word3  word4 word5
0     0  0.524038    no  llegar     a  hacer    lo
1     1  0.475962    no  llegar     a  hacer    lo

model : NaiveBayes , score = 0.524038
model : LinearSVM , score = 0.524038
model : RBFSVM , score = 0.524038
model : DecisionTree , score = 0.524038
model : RandomForest , score = 0.524038
model : AdaBoost , score = 0.524038
----------------------------------------------

file name : 22+12_30+12_110_29+113_1_30+113_1_110_29+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 55

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1     word2 word3   word4
0     0  0.196140  tres  pregunta   muy  amplio
1     1  0.200965  tres  pregunta   muy  amplio
2     2  0.200965  tres  pregunta   muy  amplio
3     3  0.200965  tres  pregunta   muy  amplio
4     4  0.200965  tres  pregunta   muy  amplio

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.18761920526265205
model : RBFSVM , score = 0.18761920526265205
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.10754406011611722
----------------------------------------------

file name : 21+10_30+10_100_29+11_30+11_100_29+33_1_30+33_1_100_29+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 6314

   rule    weight    word1        word2       word3     word4
0     0  0.139609  ninguno  responsable  claramente  definido
1     1  0.139571  ninguno  responsable  claramente  definido
2     2  0.139571  ninguno  responsable  claramente  definido
3     3  0.151054  ninguno  responsable  claramente  definido
4     4  0.151054  ninguno  responsable  claramente  definido
5     5  0.139571  ninguno  responsable  claramente  definido
6     6  0.139571  ninguno  responsable  claramente  definido

model : NaiveBayes , score = 0.13484570998686124
model : LinearSVM , score = 0.1491420531697449
model : RBFSVM , score = 0.1491420531697449
model : DecisionTree , score = 0.1357829061167114
model : RandomForest , score = 0.1049334948840881
model : AdaBoost , score = 0.11366428395684831
----------------------------------------------

file name : 30_64+30_91+30_108_68+100_67+100_63_64+100_63_91+100_63_108_68+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 14

   rule    weight word1  word2 word3     word4
0     0  0.144291  sólo  hacer    de  ostentar
1     1  0.142893  sólo  hacer    de  ostentar
2     2  0.140671  sólo  hacer    de  ostentar
3     3  0.144291  sólo  hacer    de  ostentar
4     4  0.144291  sólo  hacer    de  ostentar
5     5  0.142893  sólo  hacer    de  ostentar
6     6  0.140671  sólo  hacer    de  ostentar

model : NaiveBayes , score = 0.1442908557091443
model : LinearSVM , score = 0.1442908557091443
model : RBFSVM , score = 0.1442908557091443
model : DecisionTree , score = 0.1442908557091443
model : RandomForest , score = 0.14067085932914067
model : AdaBoost , score = 0.1442908557091443
----------------------------------------------

file name : 107+106_114+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 22

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight     word1 word2
0     0  0.492222  por_ello     ?
1     1  0.507778  por_ello     ?

model : NaiveBayes , score = 0.5162341376179551
model : LinearSVM , score = 0.4837658623820448
model : RBFSVM , score = 0.4837658623820448
model : DecisionTree , score = 0.4837658623820448
model : RandomForest , score = 0.4837658623820448
model : AdaBoost , score = 0.4837658623820448
----------------------------------------------

file name : 66_63+108_33_40+108_33_68_63+.csv
Rules(classes) number : 3
Words(features) number : 4
Records number : 12

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: divide by zero encountered in true_divide
  (self.sigma_[i, :]), 1)
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1 word2  word3 word4
0     0  0.332287     a    el  haber   ser
1     1  0.333856     a    el  haber   ser
2     2  0.333856     a    el  haber   ser

model : NaiveBayes , score = 0.168756715514194
model : LinearSVM , score = 0.3317720257615749
model : RBFSVM , score = 0.3317720257615749
model : DecisionTree , score = 0.168756715514194
model : RandomForest , score = 0.168756715514194
model : AdaBoost , score = 0.168756715514194
----------------------------------------------

file name : 73+47_69+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 20

   rule    weight word1  word2       word3
0     0  0.516462    lo  estar  considerar
1     1  0.483538    lo  estar  considerar

model : NaiveBayes , score = 0.2885738316797356
model : LinearSVM , score = 0.5246475627579833
model : RBFSVM , score = 0.5246475627579833
model : DecisionTree , score = 0.2885738316797356
model : RandomForest , score = 0.2885738316797356
model : AdaBoost , score = 0.2885738316797356
----------------------------------------------

file name : 76+92_63+100_40+100_68_63+.csv
Rules(classes) number : 4
Words(features) number : 3
Records number : 52

   rule    weight word1  word2 word3
0     0  0.254160    no  haber   dar
1     1  0.251783    no  haber   dar
2     2  0.247029    no  haber   dar
3     3  0.247029    no  haber   dar

model : NaiveBayes , score = 0.15103283830142405
model : LinearSVM , score = 0.22423955793981423
model : RBFSVM , score = 0.22423955793981423
model : DecisionTree , score = 0.03948810955170136
model : RandomForest , score = 0.037898620798693966
model : AdaBoost , score = 0.03948810955170136
----------------------------------------------

file name : 67+63_64+63_108_68+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 1440

   rule    weight      word1 word2   word3
0     0  0.333333  encaminar     a  colmar
1     1  0.333333  encaminar     a  colmar
2     2  0.333333  encaminar     a  colmar

model : NaiveBayes , score = 0.3036674273824966
model : LinearSVM , score = 0.30277620674779554
model : RBFSVM , score = 0.2817275907721134
model : DecisionTree , score = 0.2409576074269052
model : RandomForest , score = 0.2251987337310944
model : AdaBoost , score = 0.2475688472396243
----------------------------------------------

file name : 108_85+108_100_52+.csv
Rules(classes) number : 2
Words(features) number : 4
Records number : 6

   rule    weight word1 word2  word3 word4
0     0  0.504829  para    no  hacer    lo
1     1  0.495171  para    no  hacer    lo

model : NaiveBayes , score = 0.6778889827349154
model : LinearSVM , score = 0.3221110172650846
model : RBFSVM , score = 0.3221110172650846
model : DecisionTree , score = 0.3221110172650846
model : RandomForest , score = 0.3221110172650846
model : AdaBoost , score = 0.3221110172650846
----------------------------------------------

file name : 75_12+75_113_1+100_13+100_37_12+100_37_113_1+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 20

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1  word2 word3 word4
0     0  0.191526  allí  hacer   dos   año
1     1  0.191526  allí  hacer   dos   año
2     2  0.233895  allí  hacer   dos   año
3     3  0.191526  allí  hacer   dos   año
4     4  0.191526  allí  hacer   dos   año

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.20502695568933266
model : RBFSVM , score = 0.20502695568933266
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 38+68_64+68_108_68+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 48

   rule    weight   word1 word2   word3
0     0  0.342926  llegar     a  llevar
1     1  0.328537  llegar     a  llevar
2     2  0.328537  llegar     a  llevar

model : NaiveBayes , score = 0.2800503298865964
model : LinearSVM , score = 0.35847536180810363
model : RBFSVM , score = 0.35847536180810363
model : DecisionTree , score = 0.11863372226489452
model : RandomForest , score = 0.11863372226489452
model : AdaBoost , score = 0.15941830265683726
----------------------------------------------

file name : 94_1+97_108_12+97_108_113_1+108_95_1+108_98_108_12+108_98_108_113_1+108_33_96_1+108_33_99_108_12+108_33_99_108_113_1+108_33_113_108_1_108_12+108_33_113_108_1_108_113_1+.csv
Rules(classes) number : 11
Words(features) number : 8
Records number : 22

    rule    weight  word1 word2  word3 word4  word5 word6  word7     word8
0      0  0.099314  hasta    el      3    de  julio    de   2008  artículo
1      1  0.093227  hasta    el      3    de  julio    de   2008  artículo
2      2  0.093227  hasta    el      3    de  julio    de   2008  artículo
3      3  0.093704  hasta    el      3    de  julio    de   2008  artículo
4      4  0.088948  hasta    el      3    de  julio    de   2008  artículo
5      5  0.088948  hasta    el      3    de  julio    de   2008  artículo
6      6  0.093521  hasta    el      3    de  julio    de   2008  artículo
7      7  0.088774  hasta    el      3    de  julio    de   2008  artículo
8      8  0.088774  hasta    el      3    de  julio    de   2008  artículo
9      9  0.085781  hasta    el      3    de  julio    de   2008  artículo
10    10  0.085781  hasta    el      3    de  julio    de   2008  artículo

model : NaiveBayes , score = 0.0993142
model : LinearSVM , score = 0.0993142
model : RBFSVM , score = 0.0993142
model : DecisionTree , score = 0.0993142
model : RandomForest , score = 0.08894850000000001
model : AdaBoost , score = 0.0993142
----------------------------------------------

file name : 40_64+40_108_68+37_67+37_63_64+37_63_108_68+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 445

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule  weight  word1   word2 word3   word4
0     0     0.2  haber  entrar     a  formar
1     1     0.2  haber  entrar     a  formar
2     2     0.2  haber  entrar     a  formar
3     3     0.2  haber  entrar     a  formar
4     4     0.2  haber  entrar     a  formar

model : NaiveBayes , score = 0.15753374623659042
model : LinearSVM , score = 0.17511385970256155
model : RBFSVM , score = 0.19861279595487677
model : DecisionTree , score = 0.053446455252070986
model : RandomForest , score = 0.05822788654192368
model : AdaBoost , score = 0.07641758281833691
----------------------------------------------

file name : 7_29_29+8_29_29+9_29_29+10_108_15+10_108_14_29+10_108_1_29_29+11_108_15+11_108_14_29+11_108_1_29_29+33_1_108_15+33_1_108_14_29+33_1_108_1_29_29+.csv
Rules(classes) number : 12
Words(features) number : 6
Records number : 708

    rule    weight word1     word2 word3    word4    word5        word6
0      0  0.081911    el  convenio    de  ginebra  derecho  humanitario
1      1  0.087933    el  convenio    de  ginebra  derecho  humanitario
2      2  0.085374    el  convenio    de  ginebra  derecho  humanitario
3      3  0.083864    el  convenio    de  ginebra  derecho  humanitario
4      4  0.083349    el  convenio    de  ginebra  derecho  humanitario
5      5  0.081911    el  convenio    de  ginebra  derecho  humanitario
6      6  0.082985    el  convenio    de  ginebra  derecho  humanitario
7      7  0.082480    el  convenio    de  ginebra  derecho  humanitario
8      8  0.081071    el  convenio    de  ginebra  derecho  humanitario
9      9  0.083864    el  convenio    de  ginebra  derecho  humanitario
10    10  0.083349    el  convenio    de  ginebra  derecho  humanitario
11    11  0.081911    el  convenio    de  ginebra  derecho  humanitario

model : NaiveBayes , score = 0.04779147271034485
model : LinearSVM , score = 0.058570542697414935
model : RBFSVM , score = 0.0854309586301861
model : DecisionTree , score = 0.02643110905790252
model : RandomForest , score = 0.008685935557837875
model : AdaBoost , score = 0.019361885843466525
----------------------------------------------

file name : 27+21_106_29+10_30_106_29+10_100_29_106_29+11_30_106_29+11_100_29_106_29+33_1_30_106_29+33_1_100_29_106_29+.csv
Rules(classes) number : 8
Words(features) number : 6
Records number : 264

   rule    weight word1  word2 word3   word4 word5          word6
0     0  0.127872   uno  papel   más  activo     y  independiente
1     1  0.121875   uno  papel   más  activo     y  independiente
2     2  0.124957   uno  papel   más  activo     y  independiente
3     3  0.124957   uno  papel   más  activo     y  independiente
4     4  0.125213   uno  papel   más  activo     y  independiente
5     5  0.125213   uno  papel   más  activo     y  independiente
6     6  0.124957   uno  papel   más  activo     y  independiente
7     7  0.124957   uno  papel   más  activo     y  independiente

model : NaiveBayes , score = 0.0542559900037661
model : LinearSVM , score = 0.08926087280201091
model : RBFSVM , score = 0.12326377231319587
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0769822895774275
----------------------------------------------

file name : 20_106_29+12_29_106_29+113_23+113_24+113_14_106_29+113_1_29_106_29+.csv
Rules(classes) number : 6
Words(features) number : 5
Records number : 12

   rule    weight word1     word2      word3 word4    word5
0     0  0.168775  seis  objetivo  diferente     y  diverso
1     1  0.165523  seis  objetivo  diferente     y  diverso
2     2  0.162509  seis  objetivo  diferente     y  diverso
3     3  0.168894  seis  objetivo  diferente     y  diverso
4     4  0.168775  seis  objetivo  diferente     y  diverso
5     5  0.165523  seis  objetivo  diferente     y  diverso

model : NaiveBayes , score = 0.1687751687751688
model : LinearSVM , score = 0.16889416889416892
model : RBFSVM , score = 0.16889416889416892
model : DecisionTree , score = 0.16889416889416892
model : RandomForest , score = 0.1687751687751688
model : AdaBoost , score = 0.16889416889416892
----------------------------------------------

file name : 24+1_63_106_29+.csv
Rules(classes) number : 2
Words(features) number : 4
Records number : 6

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight        word1       word2 word3      word4
0     0  0.505526  inmigración  equilibrar     y  coherente
1     1  0.494474  inmigración  equilibrar     y  coherente

model : NaiveBayes , score = 0.3298335598322446
model : LinearSVM , score = 0.3298335598322446
model : RBFSVM , score = 0.3298335598322446
model : DecisionTree , score = 0.3298335598322446
model : RandomForest , score = 0.3298335598322446
model : AdaBoost , score = 0.3298335598322446
----------------------------------------------

file name : 96+99_108_113+113_108_1_108_113+.csv
Rules(classes) number : 3
Words(features) number : 5
Records number : 255

   rule    weight  word1 word2  word3 word4  word5
0     0  0.376928      1    de  enero    de   2003
1     1  0.329794      1    de  enero    de   2003
2     2  0.293278      1    de  enero    de   2003

model : NaiveBayes , score = 0.28492173347494804
model : LinearSVM , score = 0.3367974223858633
model : RBFSVM , score = 0.39453017910222304
model : DecisionTree , score = 0.17837654888961102
model : RandomForest , score = 0.1659894936543952
model : AdaBoost , score = 0.2195843182352461
----------------------------------------------

file name : 30+100_63+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 1076

   rule  weight             word1    word2
0     0     0.5  de_alguna_manera  ocultar
1     1     0.5  de_alguna_manera  ocultar

model : NaiveBayes , score = 0.4572205314900661
model : LinearSVM , score = 0.4647990828862173
model : RBFSVM , score = 0.2732230548762148
model : DecisionTree , score = 0.4237193577408349
model : RandomForest , score = 0.38300158878767293
model : AdaBoost , score = 0.3903416770705051
----------------------------------------------

file name : 84_69+100_73+100_47_69+.csv
Rules(classes) number : 3
Words(features) number : 4
Records number : 15

   rule    weight word1 word2  word3    word4
0     0  0.296842   hoy    lo  estar  debatir
1     1  0.406315   hoy    lo  estar  debatir
2     2  0.296842   hoy    lo  estar  debatir

model : NaiveBayes , score = 0.11115762827378055
model : LinearSVM , score = 0.2336983141481243
model : RBFSVM , score = 0.2336983141481243
model : DecisionTree , score = 0.11115762827378055
model : RandomForest , score = 0.11115762827378055
model : AdaBoost , score = 0.11115762827378055
----------------------------------------------

file name : 10_63_29+11_63_29+33_15+33_1_63_29+.csv
Rules(classes) number : 4
Words(features) number : 4
Records number : 84

   rule    weight word1    word2         word3   word4
0     0  0.247563   uno  sistema  informatizar  eficaz
1     1  0.247210   uno  sistema  informatizar  eficaz
2     2  0.257664   uno  sistema  informatizar  eficaz
3     3  0.247563   uno  sistema  informatizar  eficaz

model : NaiveBayes , score = 0.11849355553125353
model : LinearSVM , score = 0.19053970371076076
model : RBFSVM , score = 0.23823980418499188
model : DecisionTree , score = 0.0694058122852295
model : RandomForest , score = 0.046491304325740085
model : AdaBoost , score = 0.11843892392606487
----------------------------------------------

file name : 64_64+64_108_68+108_38+108_68_64+108_68_108_68+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 25

   rule    weight word1   word2 word3      word4
0     0  0.202745  para  llegar     a  conseguir
1     1  0.202745  para  llegar     a  conseguir
2     2  0.204575  para  llegar     a  conseguir
3     3  0.194967  para  llegar     a  conseguir
4     4  0.194967  para  llegar     a  conseguir

model : NaiveBayes , score = 0.1535092359942748
model : LinearSVM , score = 0.15974950555717687
model : RBFSVM , score = 0.15974950555717687
model : DecisionTree , score = 0.07794581534522631
model : RandomForest , score = 0.07560799123470986
model : AdaBoost , score = 0.15974950555717687
----------------------------------------------

file name : 60+47_68+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 16

   rule  weight word1  word2      word3
0     0     0.5    lo  poder  constatar
1     1     0.5    lo  poder  constatar

model : NaiveBayes , score = 0.3907131479265588
model : LinearSVM , score = 0.5187070811770713
model : RBFSVM , score = 0.5187070811770713
model : DecisionTree , score = 0.3907131479265588
model : RandomForest , score = 0.3907131479265588
model : AdaBoost , score = 0.3907131479265588
----------------------------------------------

file name : 38+37_64+37_108_68+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 51

   rule    weight   word1 word2 word3
0     0  0.354531  llegar     a   ser
1     1  0.322735  llegar     a   ser
2     2  0.322735  llegar     a   ser

model : NaiveBayes , score = 0.23554661057521825
model : LinearSVM , score = 0.2961067303875821
model : RBFSVM , score = 0.18448152174300372
model : DecisionTree , score = 0.1981366276139268
model : RandomForest , score = 0.19869171041483163
model : AdaBoost , score = 0.1981366276139268
----------------------------------------------

file name : 32+33_30+33_100_29+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 456

   rule    weight word1 word2    word3
0     0  0.340749    el   más  moderno
1     1  0.329626    el   más  moderno
2     2  0.329626    el   más  moderno

model : NaiveBayes , score = 0.31015551879539377
model : LinearSVM , score = 0.3302076467085666
model : RBFSVM , score = 0.33077810202475727
model : DecisionTree , score = 0.27999006952059113
model : RandomForest , score = 0.2324501225530451
model : AdaBoost , score = 0.23169006359161295
----------------------------------------------

file name : 40+69_63+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 8

   rule  weight  word1     word2
0     0     0.5  haber  escuchar
1     1     0.5  haber  escuchar

model : NaiveBayes , score = 0.25
model : LinearSVM , score = 0.25
model : RBFSVM , score = 0.25
model : DecisionTree , score = 0.25
model : RandomForest , score = 0.25
model : AdaBoost , score = 0.25
----------------------------------------------

file name : 18_106_63+17_29_106_63+31_23+31_14_106_63+31_1_29_106_63+33_29_23+33_29_14_106_63+33_29_1_29_106_63+.csv
Rules(classes) number : 8
Words(features) number : 6
Records number : 16

   rule    weight word1   word2       word3           word4 word5       word6
0     0  0.130386    el  actual  estructura  presupuestario     y  determinar
1     1  0.121098    el  actual  estructura  presupuestario     y  determinar
2     2  0.122773    el  actual  estructura  presupuestario     y  determinar
3     3  0.130386    el  actual  estructura  presupuestario     y  determinar
4     4  0.121098    el  actual  estructura  presupuestario     y  determinar
5     5  0.122773    el  actual  estructura  presupuestario     y  determinar
6     6  0.130386    el  actual  estructura  presupuestario     y  determinar
7     7  0.121098    el  actual  estructura  presupuestario     y  determinar

model : NaiveBayes , score = 0.13038626077252155
model : LinearSVM , score = 0.13038626077252155
model : RBFSVM , score = 0.13038626077252155
model : DecisionTree , score = 0.13038626077252155
model : RandomForest , score = 0.13038626077252155
model : AdaBoost , score = 0.13038626077252155
----------------------------------------------

file name : 75+100_36+100_37+.csv
Rules(classes) number : 3
Words(features) number : 2
Records number : 312

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1      word2
0     0  0.328514    no  haber_que
1     1  0.335654    no  haber_que
2     2  0.335831    no  haber_que

model : NaiveBayes , score = 0.297156053940856
model : LinearSVM , score = 0.30364650810851324
model : RBFSVM , score = 0.27833199568512473
model : DecisionTree , score = 0.29661452526235416
model : RandomForest , score = 0.27751982744798837
model : AdaBoost , score = 0.25890578456830055
----------------------------------------------

file name : 31+33_29+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 3450

   rule  weight word1   word2
0     0     0.5    el  último
1     1     0.5    el  último

model : NaiveBayes , score = 0.489499313017107
model : LinearSVM , score = 0.500640208963022
model : RBFSVM , score = 0.40714635803619653
model : DecisionTree , score = 0.4665642676145503
model : RandomForest , score = 0.45032754557246746
model : AdaBoost , score = 0.4576052390901414
----------------------------------------------

file name : 39+40_64+40_108_68+37_38+37_67+37_63_64+37_63_108_68+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 28

   rule    weight  word1   word2 word3     word4
0     0  0.159656  haber  llegar     a  alcanzar
1     1  0.136138  haber  llegar     a  alcanzar
2     2  0.136138  haber  llegar     a  alcanzar
3     3  0.159656  haber  llegar     a  alcanzar
4     4  0.136138  haber  llegar     a  alcanzar
5     5  0.136138  haber  llegar     a  alcanzar
6     6  0.136138  haber  llegar     a  alcanzar

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.15303900968914755
model : RBFSVM , score = 0.15303900968914755
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 32_64+32_108_68+33_30_64+33_30_108_68+33_100_67+33_100_63_64+33_100_63_108_68+.csv
Rules(classes) number : 7
Words(features) number : 5
Records number : 14

   rule    weight word1 word2       word3 word4      word5
0     0  0.148288    el   más  cualificar  para  organizar
1     1  0.140989    el   más  cualificar  para  organizar
2     2  0.145447    el   más  cualificar  para  organizar
3     3  0.137192    el   más  cualificar  para  organizar
4     4  0.145447    el   más  cualificar  para  organizar
5     5  0.145447    el   más  cualificar  para  organizar
6     6  0.137192    el   más  cualificar  para  organizar

model : NaiveBayes , score = 0.14828770342459316
model : LinearSVM , score = 0.14828770342459316
model : RBFSVM , score = 0.14828770342459316
model : DecisionTree , score = 0.14828770342459316
model : RandomForest , score = 0.14828770342459316
model : AdaBoost , score = 0.14828770342459316
----------------------------------------------

file name : 76+100_40+100_69_63+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 6

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1  word2      word3
0     0  0.335418    no  haber  presentar
1     1  0.317747    no  haber  presentar
2     2  0.346834    no  haber  presentar

model : NaiveBayes , score = 0.3354183354183354
model : LinearSVM , score = 0.34683434683434683
model : RBFSVM , score = 0.34683434683434683
model : DecisionTree , score = 0.34683434683434683
model : RandomForest , score = 0.31774731774731774
model : AdaBoost , score = 0.34683434683434683
----------------------------------------------

file name : 40_64+40_108_68+68_67+68_63_64+68_63_108_68+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 10

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule  weight  word1    word2 word3     word4
0     0     0.2  haber  limitar     a  realizar
1     1     0.2  haber  limitar     a  realizar
2     2     0.2  haber  limitar     a  realizar
3     3     0.2  haber  limitar     a  realizar
4     4     0.2  haber  limitar     a  realizar

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.20244410771241195
model : RBFSVM , score = 0.20244410771241195
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 99_29+113_108_14+113_108_1_29+.csv
Rules(classes) number : 3
Words(features) number : 4
Records number : 6

   rule    weight  word1 word2       word3    word4
0     0  0.336890     21    de  septiembre  próximo
1     1  0.337982     21    de  septiembre  próximo
2     2  0.325129     21    de  septiembre  próximo

model : NaiveBayes , score = 0.33688966311033686
model : LinearSVM , score = 0.33798166201833796
model : RBFSVM , score = 0.33798166201833796
model : DecisionTree , score = 0.33798166201833796
model : RandomForest , score = 0.33688966311033686
model : AdaBoost ,

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

 score = 0.33798166201833796
----------------------------------------------

file name : 22+12_30+12_110_63+113_1_30+113_1_110_63+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 10

   rule    weight word1   word2 word3         word4
0     0  0.208152   dos  colega   tan  experimentar
1     1  0.197962   dos  colega   tan  experimentar
2     2  0.197962   dos  colega   tan  experimentar
3     3  0.197962   dos  colega   tan  experimentar
4     4  0.197962   dos  colega   tan  experimentar

model : NaiveBayes , score = 0.208152
model : LinearSVM , score = 0.208152
model : RBFSVM , score = 0.208152
model : DecisionTree , score = 0.208152
model : RandomForest , score = 0.208152
model : AdaBoost , score = 0.208152
----------------------------------------------

file name : 36+37+.csv
Rules(classes) number : 2
Words(features) number : 1
Records number : 836

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight      word1
0     0  0.506138  haber_que
1     1  0.493862  haber_que

model : NaiveBayes , score = 0.5010786051719591
model : LinearSVM , score = 0.5010786051719591
model : RBFSVM , score = 0.5010786051719591
model : DecisionTree , score = 0.5010786051719591
model : RandomForest , score = 0.5010786051719591
model : AdaBoost , score = 0.5010786051719591
----------------------------------------------

file name : 18_106+17_29_106+31_24+31_14_106+31_1_29_106+33_29_24+33_29_14_106+33_29_1_29_106+.csv

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

Rules(classes) number : 8
Words(features) number : 5
Records number : 216

   rule    weight word1     word2      word3       word4 word5
0     0  0.125313    el  distinto  condición  geográfico     y
1     1  0.123135    el  distinto  condición  geográfico     y
2     2  0.127328    el  distinto  condición  geográfico     y
3     3  0.125313    el  distinto  condición  geográfico     y
4     4  0.123135    el  distinto  condición  geográfico     y
5     5  0.127328    el  distinto  condición  geográfico     y
6     6  0.125313    el  distinto  condición  geográfico     y
7     7  0.123135    el  distinto  condición  geográfico     y

model : NaiveBayes , score = 0.08375096177689977
model : LinearSVM , score = 0.06595154882580584
model : RBFSVM , score = 0.12189498544976621
model : DecisionTree , score = 0.009444793672452916
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.04690395659934957
----------------------------------------------

file name : 67_63+63_65+63_64_63+63_91_63+63_108_40+63_108_68_63+.csv
Rules(classes) number : 6
Words(features) number : 4
Records number : 12

   rule    weight   word1 word2  word3     word4
0     0  0.164068  acusar    de  haber  encargar
1     1  0.153241  acusar    de  haber  encargar
2     2  0.164068  acusar    de  haber  encargar
3     3  0.190487  acusar    de  haber  encargar
4     4  0.164068  acusar    de  haber  encargar
5     5  0.164068  acusar    de  haber  encargar

model : NaiveBayes , score = 0.16406800000000002
model : LinearSVM , score = 0.190487
model : RBFSVM , score = 0.190487
model : DecisionTree , score = 0.190487
model : RandomForest , score = 0.16406800000000002
model : AdaBoost ,

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

 score = 0.190487
----------------------------------------------

file name : 18+17_29+31_14+31_1_29+33_29_14+33_29_1_29+.csv
Rules(classes) number : 6
Words(features) number : 4
Records number : 5040

   rule    weight word1   word2     word3     word4
0     0  0.169627  suyo  propio  análisis  político
1     1  0.163536  suyo  propio  análisis  político
2     2  0.169627  suyo  propio  análisis  político
3     3  0.163792  suyo  propio  análisis  político
4     4  0.169627  suyo  propio  análisis  político
5     5  0.163792  suyo  propio  análisis  político

model : NaiveBayes , score = 0.15442273131374676
model : LinearSVM , score = 0.16483321148477884
model : RBFSVM , score = 0.17021238841374622
model : DecisionTree , score = 0.12652932765832817
model : RandomForest , score = 0.10259509639472521
model : AdaBoost , score = 0.1258932983112584
----------------------------------------------

file name : 75_64+75_108_68+100_38+100_37_64+100_37_108_68+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 40

   rule    weight    word1   word2 word3  word4
0     0  0.197488  incluso  llegar     a  poner
1     1  0.197488  incluso  llegar     a  poner
2     2  0.210048  incluso  llegar     a  poner
3     3  0.197488  incluso  llegar     a  poner
4     4  0.197488  incluso  llegar     a  poner

model : NaiveBayes , score = 0.04963963207633959
model : LinearSVM , score = 0.2079680095233451
model : RBFSVM , score = 0.2079680095233451
model : DecisionTree , score = 0.052796653155487816
model : RandomForest , score = 0.052796653155487816
model : AdaBoost , score = 0.052796653155487816
----------------------------------------------

file name : 40_64+40_91+40_108_68+37_67+37_63_64+37_63_91+37_63_108_68+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 91

   rule    weight  word1   word2 word3    word4
0     0  0.144200  haber  tratar    de  mejorar
1     1  0.141673  haber  tratar    de  mejorar
2     2  0.139854  haber  tratar    de  mejorar
3     3  0.144200  haber  tratar    de  mejorar
4     4  0.144200  haber  tratar    de  mejorar
5     5  0.141673  haber  tratar    de  mejorar
6     6  0.144200  haber  tratar    de  mejorar

model : NaiveBayes , score = 0.04232042772474502
model : LinearSVM , score = 0.13311660024331154
model : RBFSVM , score = 0.13311660024331154
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.02119754231305326
model : AdaBoost , score = 0.0653773982389182
----------------------------------------------

file name : 76_64+76_108_68+75_67+75_63_64+75_63_108_68+100_40_64+100_40_108_68+100_37_67+100_37_63_64+100_37_63_108_68+.csv
Rules(classes) number : 10
Words(features) number : 5
Records number : 140

   rule  weight  word1  word2   word3 word4 word5
0     0     0.1  ahora  haber  volver     a   ser
1     1     0.1  ahora  haber  volver     a   ser
2     2     0.1  ahora  haber  volver     a   ser
3     3     0.1  ahora  haber  volver     a   ser
4     4     0.1  ahora  haber  volver     a   ser
5     5     0.1  ahora  haber  volver     a   ser
6     6     0.1  ahora  haber  volver     a   ser
7     7     0.1  ahora  haber  volver     a   ser
8     8     0.1  ahora  haber  volver     a   ser
9     9     0.1  ahora  haber  volver     a   ser

model : NaiveBayes , score = 0.029109801540275218
model : LinearSVM , score = 0.10136400242342919
model : RBFSVM , score = 0.10136400242342919
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.05738313227876574
----------------------------------------------

file name : 99+113_108_1+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 110

   rule    weight  word1 word2      word3
0     0  0.523369     18    de  noviembre
1     1  0.476631     18    de  noviembre

model : NaiveBayes , score = 0.46647297102853236
model : LinearSVM , score = 0.4616156736822202
model : RBFSVM , score = 0.4927045780339101
model : DecisionTree , score = 0.3703357021742049
model : RandomForest , score = 0.29095544220379604
model : AdaBoost , score = 0.3344475953181826
----------------------------------------------

file name : 15+1_63_29+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 12

   rule    weight  word1      word2  word3
0     0  0.522456  norma  armonizar  común
1     1  0.477544  norma  armonizar  común

model : NaiveBayes , score = 0.17453341368671002
model : LinearSVM , score = 0.5096781499837646
model : RBFSVM , score = 0.5096781499837646
model : DecisionTree , score = 0.17453341368671002
model : RandomForest , score = 0.17453341368671002
model : AdaBoost , score = 0.17453341368671002
----------------------------------------------

file name : 79+84_63+100_42+100_45_63+100_47_63+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 15

   rule    weight word1 word2  word3 word4
0     0  0.227411    no    lo  haber   ser
1     1  0.194775    no    lo  haber   ser
2     2  0.210592    no    lo  haber   ser
3     3  0.178748    no    lo  haber   ser
4     4  0.188474    no    lo  haber   ser

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.12847496543948675
model : RBFSVM , score = 0.12847496543948675
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 22+12_30+12_100_63+113_1_30+113_1_100_63+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 30

   rule    weight word1 word2          word3            word4
0     0  0.203416  tres  tema  estrechamente  interrelacionar
1     1  0.199146  tres  tema  estrechamente  interrelacionar
2     2  0.199146  tres  tema  estrechamente  interrelacionar
3     3  0.199146  tres  tema  estrechamente  interrelacionar
4     4  0.199146  tres  tema  estrechamente  interrelacionar

model : NaiveBayes , score = 0.1325296415453355
model : LinearSVM , score = 0.19959612235054666
model : RBFSVM , score = 0.19959612235054666
model : DecisionTree , score = 0.06596999538879848
model : RandomForest , score = 0.06596999538879848
model : AdaBoost , score = 0.06596999538879848
----------------------------------------------

file name : 21_64+21_108_68+10_30_64+10_30_108_68+10_100_67+10_100_63_64+10_100_63_108_68+11_30_64+11_30_108_68+11_100_67+11_100_63_64+11_100_63_108_68+33_1_30_64+33_1_30_108_68+33_1_100_67+33_1_100_63_64+33_1_100_63_108_68+.csv
Rules(classes) number : 17
Words(features) number : 6
Records number : 34

    rule    weight    word1     word2 word3        word4 word5       word6
0      0  0.061179  nuestro  diputado   más  acostumbrar     a  intervenir
1      1  0.057171  nuestro  diputado   más  acostumbrar     a  intervenir
2      2  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
3      3  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
4      4  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
5      5  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
6      6  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
7      7  0.060875  nuestro  diputado   más  acostumbrar     a  intervenir
8      8  0.060875  nuestro  diputado   más  acostumbrar     a  intervenir
9      9  0.060875  nuestro  diputado   más  acostumbrar     a  intervenir
10    10  0.060875  nuestro  diputado   más  acostumbrar     a  intervenir
11    11  0.060875  nuestro  diputado   más  acostumbrar     a  intervenir
12    12  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
13    13  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
14    14  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
15    15  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir
16    16  0.057728  nuestro  diputado   más  acostumbrar     a  intervenir

model : NaiveBayes , score = 0.061179375528249785
model : LinearSVM , score = 0.061179375528249785
model : RBFSVM , score = 0.061179375528249785
model : DecisionTree , score = 0.061179375528249785
model : RandomForest , score = 0.05772767690892923
model : AdaBoost , score = 0.061179375528249785
----------------------------------------------

file name : 30_108_52+100_63_108_52+.csv
Rules(classes) number : 2
Words(features) number : 5
Records number : 4

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule  weight      word1    word2 word3  word4 word5
0     0     0.5  demasiado  asustar  para  hacer    lo
1     1     0.5  demasiado  asustar  para  hacer    lo

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.0
model : RBFSVM , score = 0.0
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 85+100_52+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 18

   rule    weight word1     word2 word3
0     0  0.499061    no  utilizar    lo
1     1  0.500939    no  utilizar    lo

model : NaiveBayes , score = 0.2236238975351392
model : LinearSVM , score = 0.44156793810892925
model : RBFSVM , score = 0.44156793810892925
model : DecisionTree , score = 0.2236238975351392
model : RandomForest , score = 0.2236238975351392
model : AdaBoost , score = 0.2236238975351392
----------------------------------------------

file name : 66+108_33_68+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 308

   rule    weight word1 word2    word3
0     0  0.492659     a    el  señalar
1     1  0.507341     a    el  señalar

model : NaiveBayes , score = 0.461297191301524
model : LinearSVM , score = 0.46970196445060763
model : RBFSVM , score = 0.28830592251804876
model : DecisionTree , score = 0.4122573664704467
model : RandomForest , score = 0.36884414076967253
model : AdaBoost , score = 0.37300673572156284
----------------------------------------------

file name : 42+47_63+.csv
Rules(classes) number : 2
Words(features) number : 3
Records number : 244

   rule    weight word1  word2 word3
0     0  0.499704    lo  haber   ser
1     1  0.500296    lo  haber   ser

model : NaiveBayes , score = 0.38677502238711753
model : LinearSVM , score = 0.4636285737988887
model : RBFSVM , score = 0.3184207452419576
model : DecisionTree , score = 0.3351521422881191
model : RandomForest , score = 0.35993603057560336
model : AdaBoost , score = 0.3624322759665186
----------------------------------------------

file name : 21+10_30+10_100_63+11_30+11_100_63+33_1_30+33_1_100_63+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 1120

   rule    weight word1    word2       word3           word4
0     0  0.144982   uno  sistema  totalmente  descentralizar
1     1  0.142143   uno  sistema  totalmente  descentralizar
2     2  0.142143   uno  sistema  totalmente  descentralizar
3     3  0.143223   uno  sistema  totalmente  descentralizar
4     4  0.143223   uno  sistema  totalmente  descentralizar
5     5  0.142143   uno  sistema  totalmente  descentralizar
6     6  0.142143   uno  sistema  totalmente  descentralizar

model : NaiveBayes , score = 0.1177903737614213
model : LinearSVM , score = 0.1120123893124631
model : RBFSVM , score = 0.1436045515362441
model : DecisionTree , score = 0.05609071186648488
model : RandomForest , score = 0.04315566291476371
model : AdaBoost , score = 0.08045588756829092
----------------------------------------------

file name : 96_1+99_108_12+99_108_113_1+113_108_1_108_12+113_108_1_108_113_1+.csv
Rules(classes) number : 5
Words(features) number : 6
Records number : 20

   rule    weight  word1 word2      word3 word4  word5         word6
0     0  0.241524     15    de  diciembre    de   2006  continuación
1     1  0.201304     15    de  diciembre    de   2006  continuación
2     2  0.201304     15    de  diciembre    de   2006  continuación
3     3  0.177934     15    de  diciembre    de   2006  continuación
4     4  0.177934     15    de  diciembre    de   2006  continuación

model : NaiveBayes , score = 0.0
model : LinearSVM , score = 0.2413839808040335
model : RBFSVM , score = 0.2413839808040335
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.0
----------------------------------------------

file name : 47_64+47_108_68+.csv
Rules(classes) number : 2
Words(features) number : 4
Records number : 4

   rule  weight word1   word2 word3  word4
0     0     0.5    lo  llegar     a  saber
1     1     0.5    lo  llegar     a  saber

model : NaiveBayes , score = 0.5
model : LinearSVM , score = 0.5
model : RBFSVM , score = 0.5
model : DecisionTree , score = 0.5
model : RandomForest , score = 0.5
model : AdaBoost , score = 0.5
----------------------------------------------

file name : 21+10_30+10_110_63+11_30+11_110_63+33_1_30+33_1_110_63+.csv
Rules(classes) number : 7
Words(features) number : 4
Records number : 287

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

   rule    weight word1      word2 word3    word4
0     0  0.132379  suyo  actuación   tan  decidir
1     1  0.142428  suyo  actuación   tan  decidir
2     2  0.142428  suyo  actuación   tan  decidir
3     3  0.148955  suyo  actuación   tan  decidir
4     4  0.148955  suyo  actuación   tan  decidir
5     5  0.142428  suyo  actuación   tan  decidir
6     6  0.142428  suyo  actuación   tan  decidir

model : NaiveBayes , score = 0.12117854955889858
model : LinearSVM , score = 0.11058929905981565
model : RBFSVM , score = 0.13765637162946023
model : DecisionTree , score = 0.05708629776372969
model : RandomForest , score = 0.013768958717064288
model : AdaBoost , score = 0.048194050630391144
----------------------------------------------

file name : 70+37_69+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 1756

   rule    weight  word1     word2
0     0  0.514636  estar  examinar
1     1  0.485364  estar  examinar

model : NaiveBayes , score = 0.5092376080873654
model : LinearSVM , score = 0.5155477821955644
model : RBFSVM , score = 0.4142580693139405
model : DecisionTree , score = 0.47187299992698806
model : RandomForest , score = 0.4381772239282214
model : AdaBoost , score = 0.4576496467893957
----------------------------------------------

file name : 12+113_1+.csv
Rules(classes) number : 2
Words(features) number : 2
Records number : 6242

   rule  weight word1 word2
0     0     0.5  seis   mes
1     1     0.5  seis   mes

model : NaiveBayes , score = 0.5023250356357817
model : LinearSVM , score = 0.49487183011875113
model : RBFSVM , score = 0.3587189323620225
model : DecisionTree , score = 0.4876632082487883
model : RandomForest , score = 0.4593944237711818
model : AdaBoost , score = 0.4652437067509656
----------------------------------------------

file name : 22+12_30+12_100_29+113_1_30+113_1_100_29+.csv
Rules(classes) number : 5
Words(features) number : 4
Records number : 60

   rule    weight word1 word2 word3  word4
0     0  0.208552    50  país   más  pobre
1     1  0.201767    50  país   más  pobre
2     2  0.193957    50  país   más  pobre
3     3  0.201767    50  país   más  pobre
4     4  0.193957    50  país   más  pobre

model : NaiveBayes , score = 0.03243725296195384
model : LinearSVM , score = 0.20664318571254572
model : RBFSVM , score = 0.20664318571254572
model : DecisionTree , score = 0.0
model : RandomForest , score = 0.0
model : AdaBoost , score = 0.03312666534301269
----------------------------------------------

file name : 15+14_29+1_29_29+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 777

   rule    weight     word1     word2          word3
0     0  0.336066  concepto  jurídico  indeterminado
1     1  0.331967  concepto  jurídico  indeterminado
2     2  0.331967  concepto  jurídico  indeterminado

model : NaiveBayes , score = 0.2936050137852968
model : LinearSVM , score = 0.29726552361270925
model : RBFSVM , score = 0.33627700140717914
model : DecisionTree , score = 0.2752638365628531
model : RandomForest , score = 0.16709213403780793
model : AdaBoost , score = 0.1985863322341775
----------------------------------------------

file name : 84+100_60+100_47+.csv
Rules(classes) number : 3
Words(features) number : 3
Records number : 12

   rule    weight word1 word2  word3
0     0  0.328663    no    lo  poder
1     1  0.345980    no    lo  poder
2     2  0.325357    no    lo  poder

model : NaiveBayes , score = 0.16665342755583534
model : LinearSVM , score = 0.3344504145340458
model : RBFSVM , score = 0.3344504145340458
model : DecisionTree , score = 0.16665342755583534
model : RandomForest , score = 0.1655003759407887
model : AdaBoost , score = 0.16665342755583534
----------------------------------------------

file name : 94+97_108_113+108_95+108_98_108_113+108_33_96+108_33_99_108_113+108_33_113_108_1_108_113+.csv
Rules(classes) number : 7
Words(features) number : 7
Records number : 273

   rule    weight word1 word2  word3 word4  word5 word6  word7
0     0  0.162927     a    el     27    de  abril    de   2000
1     1  0.136174     a    el     27    de  abril    de   2000
2     2  0.154397     a    el     27    de  abril    de   2000
3     3  0.130163     a    el     27    de  abril    de   2000
4     4  0.160826     a    el     27    de  abril    de   2000
5     5  0.134703     a    el     27    de  abril    de   2000
6     6  0.120809     a    el     27    de  abril    de   2000

model : NaiveBayes , score = 0.07477421659088763
model : LinearSVM , score = 0.10496404562553276
model : RBFSVM , score = 0.15827958403992717
model : DecisionTree , score = 0.00769779337779194
model : RandomForest , score = 0.02123447408436888
model : AdaBoost , score = 0.06372186683106934
----------------------------------------------

file name : 24+14_106_29+1_29_106_29+.csv
Rules(classes) number : 3
Words(features) number : 4
Records number : 789

   rule    weight  word1  word2 word3     word4
0     0  0.335496  norma  claro     y  completo
1     1  0.331636  norma  claro     y  completo
2     2  0.332868  norma  claro     y  completo

model : NaiveBayes , score = 0.32481851581061016
model : LinearSVM , score = 0.3165909792196462
model : RBFSVM , score = 0.3488859231380752
model : DecisionTree , score = 0.2606002301328052
model : RandomForest , score = 0.20003356990093957
model : AdaBoost , score = 0.22003922441900595
----------------------------------------------

file name : 60_63+47_40+47_68_63+.csv
Rules(classes) number : 3
Words(features) number : 4
Records number : 6

   rule    weight word1  word2  word3 word4
0     0  0.314649    lo  poder  haber   ser
1     1  0.342676    lo  poder  haber   ser
2     2  0.342676    lo  poder  haber   ser

model : NaiveBayes , score = 0.3146486853513146
model : LinearSVM , score = 0.34267565732434274
model : RBFSVM , score = 0.34267565732434274
model : DecisionTree , score = 0.34267565732434274
model : RandomForest , score = 0.3146486853513146
model : AdaBoost , score = 0.34267565732434274
----------------------------------------------

/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:436: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/home/aboelhamd/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:438: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)

In [13]:
# enc = OrdinalEncoder(dtype=np.int32)
# features = enc.fit_transform(data.iloc[:,2:])
enc.fit_transform([['a','b'],['c','d']])

array([[0, 0],
       [1, 1]], dtype=int32)

In [58]:
set(['a','b']).issubset(enc.categories_[0])
# enc.transform([['lo','poder']])

False

In [72]:
data = pd.read_csv(files[file], delimiter=r"\s+", header=None).dropna()
data
for i in range(len(data.values)) :
    for j in range(len(data.values[i])) :
        print(data.values[i][j])

rule
weight
word1
word2
word3
word4
0
0.314649
lo
poder
haber
ser
1
0.342676
lo
poder
haber
ser
2
0.342676
lo
poder
haber
ser

In [37]:
file='60_63+47_40+47_68_63+.csv'